### ISSUE TITLE
Installing Spiec-Easi in RStudio 

### ISSUE THREAD

**Issue by gaomrx** [zdk123/SpiecEasi#1]
Tried installing SpiecEasi in RStudio on a Windows 7 (32-bit) and got the following message  
```R
devtools::install_github("zdk123/SpiecEasi)
```
```R

Installing github repo(s) zdk123/SpiecEasi/master from hadley
Installing zdk123/SpiecEasi.zip from https://github.com/hadley/zdk123/SpiecEasi/zipball
Error in file(con, "wb") : cannot open the connection
In addition: Warning message:
In file(con, "wb") :
  cannot open file 'C:\Users\gaomrx\AppData\Local\Temp\Rtmp8sz4SH/zdk123/SpiecEasi.zip': No such file or directory
```

This seems to be a bug in [devtools] (http://stackoverflow.com/questions/9676281/install-github-returning-error-zip-file-cant-be-opened)

Installation works (sort of, still cannot find SpiecEasi package in library) after 
```R
devtools::install_github("SpiecEasi", username = 'zdk123')
```

```R
Installing github repo(s) SpiecEasi/master from zdk123
Installing SpiecEasi.zip from https://github.com/zdk123/SpiecEasi/zipball
Installing SpiecEasi
Installing dependencies for SpiecEasi:
VGAM
Installing package(s) into ‘C:/Users/gaomrx/Documents/R/win-library/2.14’
(as ‘lib’ is unspecified)
trying URL 'http://cran.rstudio.com/bin/windows/contrib/2.14/VGAM_0.9-0.zip'
Content type 'application/zip' length 4680784 bytes (4.5 Mb)
opened URL
downloaded 4.5 Mb

package ‘VGAM’ successfully unpacked and MD5 sums checked

The downloaded packages are in
	C:\Users\gaomrx\AppData\Local\Temp\Rtmp8sz4SH\downloaded_packages
* checking for file 'C:\Users\gaomrx\AppData\Local\Temp\Rtmp8sz4SH\zdk123-SpiecEasi-f70271a/DESCRIPTION' ... OK
* preparing 'SpiecEasi':
* checking DESCRIPTION meta-information ... ERROR
Required fields missing:
  Author Maintainer

See the information on DESCRIPTION files in section 'Creating R
packages' of the 'Writing R Extensions' manual.

Error: Command failed (1)
In addition: Warning message:
running command '"C:/PROGRA~1/R/R-214~1.0/bin/i386/R" CMD build "C:\Users\gaomrx\AppData\Local\Temp\Rtmp8sz4SH\zdk123-SpiecEasi-f70271a" --no-manual --no-vignettes' had status 1 
> library(SpiecEasi)
Error in library(SpiecEasi) : there is no package called ‘SpiecEasi’
```

I suggest including the alternate way of installing this package on README and would like to know why the SpiecEasi package was not findable in the library. Thanks.

**Comment by zdk123** [comment]
I suspect that your version of devtools is out of date. The issue you referenced is 2 years old. Your "alternate way" of installing github packages has actually been deprecated in the last couple version of devtools and should give the warning:

    Warning message:
       Username parameter is deprecated. Please use zdk123/SpiecEasi

I'm updating everything on my linux machine and will test it. If I can't replicate the error, I'll try on a Windows/Rstudio machine.

Thanks!

**Comment by gaomrx** [comment]
You are right. Can you tell me which version of R you are using? I have tried installing on R version 3.2.1 and 3.0.0 but some of the dependencies for Phyloseq and other packages were not available.

**Comment by zdk123** [comment]
Yes, using 3.2.1, and with ugrading the latest dependencies everything is working as expected. 

Phyloseq is only a suggested package for this SpiecEasi, so I'm not sure what problems you're having, perhaps related to this other issue (outdated Bioconductor version)? https://github.com/joey711/phyloseq/issues/424

I'm going to close this issue, but drop a line to Joey if you're still having problems fixing phyloseq.

**Comment by gaomrx** [comment]
Installation works but now I ran into this following the instructions on readme:

``` R
> huge::huge.roc(se.est$path, graph)
Computing F1 scores, false positive rates and true positive rates....done.
True Postive Rate: from 0 to 0.992126 
False Positive Rate: from 0 to 0.9249428 
Area under Curve: 0.8971873 
Maximum F1 Score: 0.9622884 
> stars.pr(se.est$merge[[se.est$opt.index]], graph)
Error: could not find function "stars.pr"
```

Honestly, I am only interested in finding the inverse covariance matrix given an n-by-m matrix where each row is a bacteria strain (OTU) and each column is the relative abundance of a person. Can you provide some instructions as to how I can do that? I am trying to get the inverse covariance matrix for doing multivariate Gaussian probability estimations. Thanks.

**Comment by zdk123** [comment]
The first error was an export statement error. This has been fixed (please update to new version).

If you know you want an inverse covariance, run SpiecEasi using the glasso method and inspect the output: obj$iCov.

I've added more detail to the README that should get you on your way. If you still have problems, it would be great if you can report it as a new issue.
Thanks!

**Comment by gaomrx** [comment]
Thanks, able to get sparse inverse covariance using glasso method.

**Comment by AndreaQ7** [comment]
I'm having the same problem with the installation

```
devtools::install_github("zdk123/SpiecEasi")
Installation failed: Timeout was reached: Connection timed out after 10015 milliseconds
```

Does anyone know how can I do to install it?

**Comment by zdk123** [comment]
@AndreaQ7 I haven't seen this error before. 

This is clearly a devtools issue: https://github.com/hadley/devtools/issues/877 suggesting you may be behind a firewall? Can you try cloning the source repo and using devtools::install_local.

Keeping this issue closed, since the error message is different. Please open a new issue if you can't resolve this. Thanks
