### ISSUE TITLE
Sign of edge changes

### ISSUE THREAD

**Issue by choon-sim** [zdk123/SpiecEasi#101]
Hi, I have produced a network using the 'mb' method.

se.mb.vanR14 <- spiec.easi(vanR14.phy, method='mb', sel.criterion="bstars")
ig_vanR14.mb <- adj2igraph(getRefit(se.mb.vanR14),vertex.attr=list(name=taxa_names(vanR14.phy)))
sebeta_vanR14.phy <- symBeta(getOptBeta(se.mb.vanR14), mode='maxabs')
edge_matrix_vanR14 = data.frame(as.matrix(sebeta_vanR14.phy))

It runs fine. But later, I had to agglomerate 3 ASVs of 1 particular species into 1 ASV (because I know that they are different 16S copies of the same strain). I re-ran the commands above. Most of the values in the edge matrix remains almost identical, but there was one major problem: a taxa that is connected to the merged ASV has a reversed sign from negative to positive interaction. This happens to be the most important piece of information I need from the analysis. If I co-plot the merged ASV and this associating taxa, they show a negative relationship. So the switch to a positive edge doesn't make sense. I am not sure what has gone wrong.

**Comment by zdk123** [comment]
Can you be a bit more precise in what the error is and also provide a reproducible example? For example, did all three ASVs exhibit the non-zero and negative terms in the coefficient matrix? 

Even then, there might not be bug in the method. The LASSO makes no guarantee of sign consistency if the input data changes. Different supports may be selected (i.e. you get a different lambda).

The scatter-plots might not be informative either - we are looking at a penalized linear model of CLR-transformed data so, for example, seeing negative correlations in count space may not be meaningful.

**Comment by choon-sim** [comment]
Sure, this is the coefficient matrix before agglomerating the three ASVs. I am showing only the taxa of interest. Bacteroides acidifaciens_14 is the taxa that changed edge sign. It is -0.35 with respect to Klebsiella_10 here.
                      | Klebsiella_10 | Klebsiella_11 | Klebsiella_32
Klebsiella_10 | 0 | 0.35447185 | 0.34366068
Klebsiella_11 | 0.35447185 | 0 | 0.00950998
Bacteroides acidifaciens_14 | -0.3521068 | 0 | 0
Klebsiella_32 | 0.34366068 | 0.00950998 | 0

This is the matrix after agglomerating the three Klebsiella ASVs. Bacteroides acidifaciens_14 is now 0.34 with respect to the merged Klebsiella.
  | Klebsiella | Bacteroides acidifaciens_14
Klebsiella | 0 | 0.349646127
Bacteroides acidifaciens_14 | 0.349646127 | 0

As mentioned, all the other values in the larger matrix are basically unchanged. 

Biologically, it is difficult to interpret the change in sign because I know that the three ASVs come from the same Klebsiella strain, so mathematically, the three of them should have perfect correlation? In that case, the sign change with Bacteroides acidifaciens is very puzzling.

**Comment by zdk123** [comment]
I'm inferring from your partial coefficient matrix that the Klebsiella's
16S are not perfectly correlated, and is especially weak between 11 and 32
(which are both conditionally independent from Bacteriodes). This could be
due to technical variability - I couldn't say.

But there are a few reasons that a coefficient could flip signs in a linear
model - multicollinearity and the Simpson's paradox, for example. Also,
since we're dealing with compositional data, combining a subset of the
components will change the whole composition.

I would be curious if what this data subset looks like when you combine
only 2 out of 3 of the Klebsiella's.
