### ISSUE TITLE
Parallelizing SparCC 

### ISSUE THREAD

**Issue by mpdoane2** [zdk123/SpiecEasi#102]
Hi,

I am keen to use this function, however have been running into issue with the amount of data I am attempting to analyze. I have a matrix of 53 rows x 31128 columns (OTU data). I end up running into a wall with space allocation or time spent running on the resources available to me. I am wondering you have advice on parallizing the function to reduce space/time constraints?

Thank you in advance

**Comment by zdk123** [comment]
At a data set this size you'd need 156 GB of memory just to store the final list of correlation matrices in memory from a single inner loop (20 replicates * 31128^2 * 8 bytes). This obviously blows up massively if you are attempting to bootstrap.

I could parallelize the inner loop by swapping in a `mclapply` function, but this doesn't solve the memory problem - we'd need to implement a different kind of batching system.

On the other hand, have you thought about filtering or aggregating OTUs in your data set? Typically, correlations on large datasets with small samples are likely to be false positives.

**Comment by mpdoane2** [comment]
Hey mate,

Thanks for getting back with me. I agree with the stated concern for the issue of false positives. I do have a means of reducing the dataset way down and can reach aprroximately 13000 OTU's. From calculating this, a stored list would be approximately 28 gb, which is well within the storage limits of my system. 

I am interested in the parallelize option you mention above. Do you think you could implement this into the sparcc () for R? I would be very appreciative and I know some colleagues I work with here in Sydney will be very interested as well.

Cheers,
Mike

**Comment by zdk123** [comment]
Yes I can start developing this in a branch. A single machine parallelization is a simple tweak, implementing a batchtools workflow will be a bit more complicated.

**Comment by zdk123** [comment]
Can you try out the [`mcsparcc`](https://github.com/zdk123/SpiecEasi/tree/mcsparcc) branch?
