### ISSUE TITLE
matrix values for edges between specific nodes

### ISSUE THREAD

**Issue by aves920** [zdk123/SpiecEasi#104]
Hi, I've made a network using the 'mb' method and I'm interesting in looking at all interactions that occur with one OTU.  I've tried to export the matrix values but I can't figure out how to append the OTU/taxonomic information to the matrix, so that I can determine whether it's a + or -ve relationship between the relevant OTUs. I thought about separately computing Pearson's correlations for the OTU-OTU edges I'm interested in but that might not be appropriate? 
Would be great if you could please help :)

spiec.mb <- spiec.easi(phyloseqobj.f, method="mb",icov.select.params=list(rep.num=20))
spiec.graph <- adj2igraph(getRefit(spiec.mb), vertex.attr=list(name=taxa_names(phyloseqobj.f)))
sbeta_graph <- symBeta(getOptBeta(spiec.mb), mode='maxabs')
edge_matrix = data.frame(as.matrix(sbeta_spiec_graph))

**Comment by zdk123** [comment]
I would do something like this:
```
rownames(sbeta_graph) <- colnames(sbeta_graph) <- taxa_names(phyloseqobj.f)
edgelist <- Matrix::summary(phyloseqobj.f)
```

Then you can map lineages to taxa names via `tax_table(phyloseqobj.f)`.

Let me know if this works, since I'm just typing this out these commands by memory.

**Comment by aves920** [comment]
Works perfectly for what I need using:

sbeta_graph <- symBeta(getOptBeta(spiec.mb), mode='maxabs')
rownames(sbeta_graph) <- colnames(sbeta_graph) <- taxa_names(phyloseqobj.f)
edge_matrix = data.frame(as.matrix(sbeta_sgraph))

Thank you so much!
