### ISSUE TITLE
SpiecEasi without normalization

### ISSUE THREAD

**Issue by hmamine** [zdk123/SpiecEasi#106]
Hello, 
I have two type of data sets, 16S and ITS count tables that I have merged to one phyloseq object.
I am trying to make a network out of these, however the method do internal normalization that is not appropriate in this case (different runs/sequencing depths). Is there a work around this, or providing rel. abundance matrix as input without the internal normalization possible?

**Comment by hmamine** [comment]
I could figure out that I can use multi.spiec.easi, however I am running to the following error that I could not figure out why.
multi.spiec.easi(list(physeq_Bac, physeq_Fun), method="glasso")
Error in rowSums(data) : 'x' must be an array of at least two dimensions
I would very much appreciate your help inhere.

**Comment by zdk123** [comment]
Thanks for the bug report.

This seems to be the same error as a previous issue, #75. This could be a reversion or I'm not correctly handling phyloseq objects. Let me see if I can duplicate with a test example.

**Comment by zdk123** [comment]
I can't reproduce this error. Can you make sure you're using the latest version of SpiecEasi and run the example in the [README](https://github.com/zdk123/SpiecEasi#cross-domain-interactions).

Otherwise, it might be a data-specific error (formatting, etc).

**Comment by hmamine** [comment]
Thank you, it was indeed an old version bug. 
Best

**Comment by zdk123** [comment]
great, thanks!
