### ISSUE TITLE
call to spiec.easi renders new result 

### ISSUE THREAD

**Issue by ghost** [zdk123/SpiecEasi#107]
Hello,

I realised that I get different results from running the spiec.eaci function using the updated package version. I then downgraded to 0.1.4 but still am not getting my old result back (although more close to what it was)

my function call is
se.est_V6.02 <- spiec.easi(phy_V6_02, method='mb', lambda.min.ratio=1e-2, nlambda=20, icov.select.params=list(rep.num=50))

any pointers as to why this might be?

thanks a lot!

**Comment by zdk123** [comment]
Do you happen to have your old results saved? It would helpful to quantify the precise differences you're seeing.

The other change was the 1.3 release of huge. Perhaps fall back to 1.2:
https://cran.r-project.org/src/contrib/Archive/huge/

**Comment by melclerc87** [comment]
As a matter of fact I do have the old object saved! I´d be more than happy to provide you with the old object and the one generated by the new package version? would that help?

**Comment by zdk123** [comment]
I think so, yes (along with the input data). You can send it via email (link in profile)

**Comment by melclerc87** [comment]
I just sent you the data, thanks in advance for your time spent on this!

**Comment by zdk123** [comment]
Please try again with huge 1.3.4... a fresh R install might be necessary as well.

**Comment by ltipton** [comment]
Do either of you have any more information about this discrepancy? Why it happened? How different the results are? Which result is correct? 
Thanks for sharing!

**Comment by zdk123** [comment]
I'm not entirely sure... the source code was re-implemented so it's tricky to compare directly. Certainly, it seems that the screening rule was pulled out and implemented as an independent method. I'm considering 1.3.4 to be 'correct' since it is consistent with most (all?) of the published results.
