### ISSUE TITLE
How do you install the 1.0.7 patch?

### ISSUE THREAD

**Issue by smcbride1983** [zdk123/SpiecEasi#108]
I am trying to install the most recent patch, do I need a previous version of the package as well?

**Comment by zdk123** [comment]
Nothing special needs to be done since the 1.0.7 PR (#98) has been integrated. Just reinstall from scratch.

**Comment by smcbride1983** [comment]
Thanks. For some reason it did not work the first time I tried doing that. But, it loaded the patch this time!
