### ISSUE TITLE
sign of associations?

### ISSUE THREAD

**Issue by ctekellogg** [zdk123/SpiecEasi#109]
Hello,
I am trying to figure how to plot whether an edge has a negative or positive association.  

```library(Matrix)
sebeta <- symBeta(getOptBeta(spiec.outpND.mb))
elist.mb <- summary(sebeta)
edge_matrix_SE_mbND = data.frame(as.matrix(sebeta))
```
#check that there are both positive and negative edges
```
positive=length(edge_matrix_SE_mbND[edge_matrix_SE_mbND>0])/2 #9418
negative=length(edge_matrix_SE_mbND[edge_matrix_SE_mbND<0])/2 #1275
total=length(edge_matrix_SE_mbND[edge_matrix_SE_mbND!=0])/2 #10693
```
#make an igraph object
```
test<- adj2igraph(getRefit(spiec.outpND.mb),
                  edge.attr=elist.mb,
                  vertex.attr=list(name=taxa_names(prunedSet.nd)))
```
#now make a matrix that has info for coloring the nodes by sign.
```
otu.ids=colnames(spiec.outpND.mb$data)
edges=E(test)
edge.colors=c()
for(e.index in 1:length(edges)){
        adj.nodes=ends(test,edges[e.index])
        xindex=which(otu.ids==adj.nodes[1])
        yindex=which(otu.ids==adj.nodes[2])
        beta=edge_matrix_SE_mbND[xindex,yindex]
        if(beta>0){
                edge.colors=append(edge.colors,"forestgreen")
        }else if(beta<0){
                edge.colors=append(edge.colors,"red")
        }
}
E(test)$color=edge.colors
```

I got this code from an online tutorial here: http://psbweb05.psb.ugent.be/conet/microbialnetworks/solutions.php#betamat

But for some reason when I run the for loop i get the following error: 
```Error in if (beta > 0) { : argument is of length zero```

Any thoughts about why I might be getting this error, since I know there are both positive and negative edges....

Colleen

**Comment by ctekellogg** [comment]
i wonder if the root of the problem might be in this line of code:
```otu.ids=colnames(spiec.outpND.mb$data)
```
as spiec.outpND.mb$data yields a NULL 

I'll see if I can figure out what object i should use for this.... or if anyone knows off hand that would be amazingly helpful.

**Comment by zdk123** [comment]
That tutorial is out of date. Try `spiec.outpND.mb$est$data`.

**Comment by ctekellogg** [comment]
brilliant. thank you! worked like a charm.
