### ISSUE TITLE
multithreading

### ISSUE THREAD

**Issue by alper1976** [zdk123/SpiecEasi#11]
I am running SpiecEasi on a computer cluster and would like to run it on multiple nodes. In the manual it is mentioned that the ncores flag allows to set the number of cores, however I get an error message.

**Comment by zdk123** [comment]
Hi @alper1976. Can you provide the message and a MWE please?

**Comment by alper1976** [comment]
se.mb.otu = spiec.easi(otutab, method='mb', lambda.min.ratio=1e-2, nlambda=20, icov.select.Normalizing/clr transformation of data with pseudocount ...
Inverse Covariance Estimation with mb ...
Error in (function (x, lambda = NULL, nlambda = NULL, lambda.min.ratio = NULL,  :
  unused argument (ncores = 1)


On 29 Nov 2016, at 19:15, Zachary Kurtz <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @alper1976<https://github.com/alper1976>. Can you provide the message and a MWE please?

**Comment by alper1976** [comment]
Sorry

That was the command

se.mb.otu = spiec.easi(otutab, method='mb', lambda.min.ratio=1e-2, nlambda=20, icov.select.params=list(rep.num=50), ncores = 1)


On 30 Nov 2016, at 08:37, Alexander Eiler <alexander.eiler@ebc.uu.se<mailto:alexander.eiler@ebc.uu.se>> wrote:

 se.mb.otu = spiec.easi(otutab, method='mb', lambda.min.ratio=1e-2, nlambda=20, icov.select.Normalizing/clr transformation of data with pseudocount ...
Inverse Covariance Estimation with mb ...
Error in (function (x, lambda = NULL, nlambda = NULL, lambda.min.ratio = NULL,  :
  unused argument (ncores = 1)


On 29 Nov 2016, at 19:15, Zachary Kurtz <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @alper1976<https://github.com/alper1976>. Can you provide the message and a MWE please?

**Comment by zdk123** [comment]
Ok, this is my fault for the function not being well documented... (will be improved in a future update). The ncore argument is one of the `icov.select.params` not to spiec.easi directly. Please run it as:

    se.mb.otu = spiec.easi(otutab, method='mb', lambda.min.ratio=1e-2, nlambda=20, icov.select.params=list(rep.num=50, ncores = 1))

**Comment by alper1976** [comment]
Thanks for the swift response. We will acknowledge your help.

Best,

Alex

On 30 Nov 2016, at 21:56, Zachary Kurtz <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, this is my fault for the function not being well documented... (will be improved in a future update). The ncore argument is one of the icov.select.params not to spiec.easi directly. Please run it as:

se.mb.otu = spiec.easi(otutab, method='mb', lambda.min.ratio=1e-2, nlambda=20, icov.select.params=list(rep.num=50, ncores = 1))

**Comment by zdk123** [comment]
no problem! You can also email me directly if you have any usage questions that don't look like bugs.
