### ISSUE TITLE
icov.select depreciated question

### ISSUE THREAD

**Issue by cbwall** [zdk123/SpiecEasi#110]
I managed to run the 'sparseiCov' function for a centered and log-transformed otu table (otu.clr), but am having trouble resolving the replacement for 'icov.select' for my est object (see below)

#build graph (2 steps)
otu.est <- sparseiCov(otu.clr, method='glasso') # this runs
otu.sel <- icov.select(otu.est, criterion='stars', ncores=6) # this gives error

I understand icovselect is for lambda penalty selection. Is this now integrated into the 'spiec.easi' command, and how are the boundaries best selected (i.e. lambda.min.ratio=xxx, nlambda=xx)?

**Comment by zdk123** [comment]
`icov.select` function doesn't exist in the current release or in the main branch of this repo. It has been deprecated in favor of the `pulsar` package, which I also maintain. 

The best values for `lambda.min.ratio` and `nlambda` are quite dataset specific, so I would recommend running the code a few times with different values s.t. the variability statistic is as close to the StARS threshold as possible. There is a short rundown in the README: https://github.com/zdk123/SpiecEasi#troubleshooting
