### ISSUE TITLE
Questions: After running SpiecEasi, do I need to delete the isolated nodes before using igraph to calculate topological property of the graph

### ISSUE THREAD

**Issue by Lei0509** [zdk123/SpiecEasi#112]
Hi @zdk123 , 

This is Lei again. Thank you so  much for your patience. 
I got some result after running SpiecEasi and came to have another questions when I wanted to calculate the topological statistic. 

Do I need to delete the isolated nodes (the correlation is 0) before using igraph to calculate topological property of the graph? How the results can be different with deleting and without deleting? 

Thank you!!

**Comment by zdk123** [comment]
it really depends on the scientific question. This is sort of out of scope for this issue tracker, but please send an email if you're still working on this. closing.
