### ISSUE TITLE
Determining lambda on OTU table, but plotting taxonomy data

### ISSUE THREAD

**Issue by marakozic** [zdk123/SpiecEasi#113]
Hello,

I've generated synthetic data from my OTU table (raw counts) and determined lambda.min.ratio that I should use. However, in order to plot the taxa (instead of OTUs) as nodes, I need to run spiec easi on a phyloseq object containing taxa abundance, instead of raw counts. In this case, do I still use lambda.min.ratio I got for OTU raw counts? If not, how do I choose lambda.min.ratio? @zdk123

**Comment by zdk123** [comment]
Somehow I missed this issue, apologies!

lambda.min.ratio sets the lower limit of search space for the optimal lambda. Unless the optimal lambda is very small, this parameter shouldn't affect the results. If you use the same value and the optimal lambda is found, changing the lower bound shouldn't change the results very much.
