### ISSUE TITLE
set number of cores for sparcc function

### ISSUE THREAD

**Issue by CoraHoerstmann** [zdk123/SpiecEasi#115]
Hi,

sorry I might have missed this, but is there the possibility in the sparcc function to set the number of cores?

**Comment by zdk123** [comment]
For bootstrapping SparCC, yes.

```
sparccboot(..., ncores=4)
```

The inner process is not parallelized to avoid the scenario nested parallelization within bootstraps. If this is a deal breaker, the code could be modified to allow it.

**Comment by CoraHoerstmann** [comment]
Thank you for your response.
I saw the previous post on mcsparcc, but only found that you can parallelize the job but not how you restrict it to a certain number of cores?

**Comment by zdk123** [comment]
supply an integer to the `ncpus` argument 
https://github.com/zdk123/SpiecEasi/blob/mcsparcc/R/spaRcc.R#L12

**Comment by CoraHoerstmann** [comment]
That's what I did but no matter what I set for the ncpus it ignores the number of set cpus and uses all available resources instead.

**Comment by zdk123** [comment]
I'm not doing anything fancy other than calling parallel::mclapply. Try playing around with that function on your system.
