### ISSUE TITLE
Impact of Sample Size on Network Inference

### ISSUE THREAD

**Issue by kspeeriful** [zdk123/SpiecEasi#117]
Hi!

I'm attempting to construct networks on different subsets of my data and was sometimes running into errors that led me to Issue #111, referenced here, it is recommend to only infer networks when your sample size is greater than 40.

> It's definitely a sample size issue, but I don't have a good heuristic for you.  The lambda penalty interacts with the sample size via the sample correlation matrix. 
> So you'd need to control for the the noise in the correlation matrix, the sample size, number of OTUs and the magnitude of the true correlations, plus other sources of statistical error.
> 
> What you may be seeing is stability issues in the MB method when the dataset is extremely noisy. Especially since to do model selection, we run 80% subsamples through the method... so 5 full samples is really only 4 samples. And since 5 choose 4 = 5, you can't actually get a useful StARS summary statistic anyway.
> 
>  I would only trying network inference over hundreds of samples, and probably no fewer than 40.
> 
> 

_Originally posted by @zdk123 in https://github.com/zdk123/SpiecEasi/issues/111#issuecomment-545474371_

I'm a little confused why this might be and how this relates to my own data. I have 10 datasets that I've inferred networks for using the MB method, a range of lambda.min.ratios, and an nlambda of 100. In each dataset, the sample size ranged from 10-22. Stability of networks was at least 0.049. I only ran into errors when I took the three datasets with the largest sample sizes and subsampled them to 10 samples each.

Does the minimum recommended sample size vary depending on how many bacterial taxa are associated with each sample? Or is it possible to get networks with stability close to 0.05 that are not accurate when sample sizes are lower than 40?

Thanks for any clarification!
Kelly

**Comment by zdk123** [comment]
Thanks for the question @kspeeriful! Yes the number of taxa definitely matters. The false discovery rate is related to the number of parameters you are trying to estimate, as well as the amount of data available for fitting those observations. The magnitude of the actual correlations matter as well - which makes it difficult to make specific recommendations, unfortunately.

**Comment by kspeeriful** [comment]
@zdk123 that makes sense to me -- thanks for clarifying! If I am estimating a network from 10 samples (or some other small sample size) and the stability is close to 0.05 with high number of StARS resamplings (rep.num=999), can I feel confident that the estimated network is reliable? Or am I misunderstanding the stability metric, and it is not a reflection of the precision of a network? Is there a better way to assess the quality of the network I estimate in terms of precision and accuracy?

**Comment by zdk123** [comment]
I recommend reading the [original StARS paper](https://arxiv.org/pdf/1006.3316.pdf), or our [extension](https://arxiv.org/abs/1605.07072).

> StARS seeks the minimum amount of regularization that results in a sparse graph whose edge set is reproducible under random subsampling of the data at a fixed proportion.

In other words, we seek a sparsity level which is likely (generally 95%) to produce a graph that contains the true edge set. Unlike, say bootstrapping, the goal is not to constrain false positives, per se. But this also means we can get away with 20-100 subsamples rather than thousands of bootstraps as well as estimating the null distribution.

**Comment by kspeeriful** [comment]
Thanks! I think my confusion on the appropriate number of reps to use originated from the info here:

https://mibwurrepo.github.io/Microbial-bioinformatics-introductory-course-Material-2018/inference-of-microbial-ecological-networks.html

**Comment by kspeeriful** [comment]
Hi @zdk123!
After reading both Liu et al. (2010) and Müller et al. (2016), I'm still a bit stuck. In cases where sample size is low and the number of bacteria in a graph is also low, would StARS struggle to assess graph stability, because subsample sizes would be small?

From Müller et al. (2016): 
Let b(n) be the size of a subsample with 1 < b(n) < n with b(n) = [10√n] the recommended choice.

In order to meet the recommended b(n), but keep the b(n) below the total sample size, you would need to have ~101 samples. Am I understanding this correctly? 

Can you tell me more about what the recommended b(n) is based on?  

Thank you!

**Comment by zdk123** [comment]
10√n is not a technical requirement. For example SPIEC-EASI chooses b(n) = .8*n instead.
