### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by ali930** [zdk123/SpiecEasi#119]
Hi,

Is it possible to run spieceasi if there is some missing data in the dataset?

Thanks!

**Comment by zdk123** [comment]
Not at this time. How much missing data do you have and what's the structure?

**Comment by ali930** [comment]
Hi Zachary,

Thanks for your reply. 

My dataset is of 300 samples x 250 ASVs (30 mice each fed 10 diets sequentially). What we noticed was that some ASVs are always below the detection threshold in some mice, so we cannot confidently say if the ASV is not responding to the diet or simply absent from the animal. 

What I wanted to do was to perform a network analysis with all the data, then compare against a network based on a filtered dataset with removal of the zeros from the mice where a particular ASV is never present. This means that there will be a scattering of NAs across the dataset. I was thinking that a network analysis on this filtered dataset would remove some noise and give more confident results. Any suggestions?

Thanks!

**Comment by zdk123** [comment]
The underlying assumption is that observed zero counts for OTUs/ASVs are actually under the detection limit.
