### ISSUE TITLE
Installation error 127 : missing gtar

### ISSUE THREAD

**Issue by AdamSorrel** [zdk123/SpiecEasi#120]
When using your provided version of installation from within R:
```
library(devtools)
install_github("zdk123/SpiecEasi")
library(SpiecEasi)
```
I have run into issues with gtar, which seems to not have existed in my system. This issue blocked my installation with a semi-unhelpful message. Creating a link from existing tar to gtar in /bin using 
`ln -s /bin/tar /bin/gtar` resolved the issue. 
I am sorry, I no longer have the error message or the will to go recreate the scenario. I don't know how common this issue is, but since the solution is so simple you might want to leave this message hanging out here or even add this information into the installation section. Up to  you. 
Cheer,
Adam

**Comment by zdk123** [comment]
Thanks for finding and fixing a potential issue. This seems to be related to devtools or perhaps utils interacting with conda in a weird way.
https://github.com/r-lib/devtools/issues/379
