### ISSUE TITLE
Corelations in sparcc pvalue output are different than in the original output

### ISSUE THREAD

**Issue by cramjaco** [zdk123/SpiecEasi#121]
I ran pval.sparccboot and the correlation values that it returns are different than the original ones that sparcc returns. Could you tell me what I am missing here?

For, instance, I am pulling the tara oceans data.

```
TaraPhyla <- read_tsv("https://www.ebi.ac.uk/metagenomics/api/v1/studies/MGYS00000410/pipelines/2.0/file/ERP001736_phylum_taxonomy_abundances_v2.0.tsv", row.names = NULL)
```

And I process them so that they are the right format for sparcc

```
TaraPhylaMtx <- TaraPhyla %>%
  select(-kingdom)  %>% # remove kingdom column
  filter(phylum != "unassigned") %>%
  mutate(phylum = make.unique(phylum)) %>% # if you don't remove "unassigned, there are two phyla with this name and you have problems without this line
  column_to_rownames(var = "phylum") %>% # turn phylum into row.names of data frame
  as.matrix() %>% # transmogrify data.frame into matrix
  t() %>% # transpose, so the OTUs are the columns and samples are the rows
  pass
```

If I run sparcc I get a correlation matrix

```
out <- sparcc(TaraPhylaMtx)

cout <- rownames(out$Cor) <- colnames(TaraPhylaMtx)
colnames(out$Cor) <- colnames(TaraPhylaMtx)
rownames(out$Cov) <- colnames(TaraPhylaMtx)
colnames(out$Cov) <- colnames(TaraPhylaMtx)
cout <- as.data.frame(out$Cor)

cout[1:5, 1:5]
```

> `              Crenarchaeota Euryarchaeota Parvarchaeota          AC1         AD3
Crenarchaeota     1.0000000     0.3227054   0.103307474 -0.128419020 -0.16858427
Euryarchaeota     0.3227054     1.0000000  -0.243501583 -0.178192828 -0.14105501
Parvarchaeota     0.1033075    -0.2435016   1.000000000  0.002226389 -0.05543442
AC1              -0.1284190    -0.1781928   0.002226389  1.000000000  0.09011223
AD3              -0.1685843    -0.1410550  -0.055434424  0.090112226  1.00000000`

Then I bootstrap and calculate p values as follows.

```
out2 <- sparccboot(TaraPhylaMtx, R = 100)

outP <- pval.sparccboot(out2)
```

And reshape them according to the advice provided in this issue
https://github.com/zdk123/SpiecEasi/issues/17

```{r}
cors <- outP$cors

sparCCpcors <- diag(0.5, nrow = dim(out$Cor)[1], ncol = dim(out$Cor)[1])
sparCCpcors[upper.tri(sparCCpcors, diag=FALSE)] <- cors
sparCCpcors <- sparCCpcors + t(sparCCpcors)

rownames(sparCCpcors) <- colnames(TaraPhylaMtx)
colnames(sparCCpcors) <- colnames(TaraPhylaMtx)

sparCCpcors[1:5, 1:5]
```

 
I get an output that looks like this:

```

>               Crenarchaeota Euryarchaeota Parvarchaeota         AC1         AD3
> Crenarchaeota    1.00000000     0.3248001    0.09544598 -0.12346530 -0.14181158
> Euryarchaeota    0.32480005     1.0000000   -0.25500113 -0.16820469 -0.10189749
> Parvarchaeota    0.09544598    -0.2550011    1.00000000 -0.02207954 -0.03387205
> AC1             -0.12346530    -0.1682047   -0.02207954  1.00000000  0.07149032
> AD3             -0.14181158    -0.1018975   -0.03387205  0.07149032  1.00000000

```

These `sparCCpcors` values look similar to, but slightly different than the `cout` values provided directly by sparCC. Specifically, while they are not quite the same, the have the same sign and similar magnitude to the others. Could you explain why these are different and which values I should be using for subsequent analysis? Thanks!

**Comment by zdk123** [comment]
What you are missing is that SparCC contains some random elements - e.g. sample compositions are estimated by sampling from a dirichlet distributions, so any two runs (even without bootstrapping) will get you numerically different results.
Try `set.seed`. I'm not sure if this will work in the bootstrap case, since I'm not sure if the `bootstrap` package handles passing random seeds to parallel jobs, but I can add this feature if necessary.
