### ISSUE TITLE
bootstrapped/replicated network list from spiec.easi() object

### ISSUE THREAD

**Issue by mchialva** [zdk123/SpiecEasi#128]
Hi,
I was wondering if there is a way to extract from spiec.easi(...,method='mb') object a list containing bootstrapped networks or something similar. Indeed, I'm interested in comparing networks parameters (such as transitivity, average degree and distance path) and I'd need replications on which perform statistical testing.
I found some list of networks such as:

mb.dataset[["select"]][["stars"]][["merge"]]

and others in spiec.easi() generated object, but I'm unsure if I can use those as replicates..
Thank you!

**Comment by zdk123** [comment]
The networks from subsampled data are not saved, but I've been always open to adding additional summary criteria to the `pulsar` package.
Do you mind transferring this issue to https://github.com/zdk123/pulsar

thanks!

**Comment by mchialva** [comment]
Thanks a lot, I re-posted the issue on pulsar repository page..
