### ISSUE TITLE
SpiecEasi parameters

### ISSUE THREAD

**Issue by choon-sim** [zdk123/SpiecEasi#130]
Hi,

I run SpiecEasi (v1.0.6) using the following command:
 
se <- spiec.easi(phy, method='mb', sel.criterion="stars")
 
In your tutorial on Github, there are additional parameters such as :
lambda.min.ratio=1e-2, nlambda=20, pulsar.params=list(rep.num=50))
 
I am wondering when these parameters are necessary.
 
In my network, stability is less than 0.05.
> getStability(se)
[1] 0.03746698
 
Do I change the parameters above until I get as close to 0.05 as possible?
 
I am also building several networks. If parameters should be optimized, do I optimize for 1 network (e.g. the control network), and apply the same settings to other networks?

Thanks,
Choon

**Comment by zdk123** [comment]
Correct. See [troubleshooting](https://github.com/zdk123/SpiecEasi#troubleshooting) section of the readme.

Reusing paramters is an interesting idea, but I haven't testing the performance. As of now, I'd recommend parameter tuning on a per dataset basis.
