### ISSUE TITLE
No edges appearing in network plot despite expectations

### ISSUE THREAD

**Issue by averyet** [zdk123/SpiecEasi#132]
Hey,

I'm a student working on a research project and quite new to SpiecEasi. It seems like this package is more geared toward microbiology, but I'm using it to assess spatial relationships of marine fauna. I was able to run the mb and glasso methods (haven't tried sparcc yet) on a subset of my data that includes 28 sample sites and 20 species. However, when I plot the network there are no edges between any of the nodes. This was surprising given that I've run the same dataset through other network association and cooccurrence packages and saw pretty clear relationships between some of the species. Is my data/sample size the issue here? I've attached an example that captures the general picture of what I'm working with. 
[example input.xlsx](https://github.com/zdk123/SpiecEasi/files/4794050/example.input.xlsx)

Also, here is my code, which is probably flawed as well. Any help or advice would be much appreciated!

install.packages("devtools")
library(devtools)
library(igraph)
install_github("zdk123/SpiecEasi")
library(SpiecEasi)

setwd("~/Documents/Project/Matrices & Dataframes")
SEdata <- read.csv("dataset.csv", row.names = 1)
numericmatrix <- data.matrix(SEdata, rownames.force = NA)

#SPIECEASI pipeline                             
MBmethod <- spiec.easi(numericmatrix, method='mb', lambda.min.ratio=1e-2, 
                          nlambda=15, icov.select.params=list(rep.num=50))

GLmethod <- spiec.easi(numericmatrix, method='glasso', lambda.min.ratio=1e-2,
                          nlambda=20, icov.select.params=list(rep.num=50))

#make igraph objects
ig.MB <- adj2igraph(getRefit(MBmethod))
ig.GL <- adj2igraph(getRefit(GLmethod))

vsize <- rowMeans(clr(SEdata, 1))+6
am.coord <- layout.fruchterman.reingold(ig.MB)

#SPIECEASI visualization
par(mfrow=c(1,3))

plot(ig.MB, layout=am.coord, vertex.size=vsize, vertex.label=NA, main="MB network")
plot(ig.GL, layout=am.coord, vertex.size=vsize, vertex.label=NA, main="glasso network")

**Comment by zdk123** [comment]
Check out the [troubleshooting](https://github.com/zdk123/SpiecEasi#troubleshooting) section in the README. Are you getting the warning  `Optimal lambda may be larger than the supplied values` in the output? This means you are not sampling the 'early' part of the lambda path finely enough. I recommend bumping `lambda` up to 50 or and `lambda.min.ratio` probably can be higher as well (try `1e-1`).

**Comment by averyet** [comment]
I totally missed the troubleshooting section, thank you. Yes, I was getting that warning and adjusting the lambda values in small increments which clearly weren't enough. Bumped them up to 100 so the stabilities are much closer to 0.05. And the plots are showing edges now. Thanks again for explaining!
