### ISSUE TITLE
variance stabilizing transformation before SpiecEasi?

### ISSUE THREAD

**Issue by TaylerChicoine** [zdk123/SpiecEasi#139]
Hello,
I recently came across your preprint https://www.biorxiv.org/content/10.1101/406264v2.abstract
and wondered if, given these results, you would recommend normalizing a count dataset with deseq2 variance stabilizing transformation before calculating co-occurrence values with SpiecEasi? 

Thanks!

**Comment by zdk123** [comment]
The tl;dr is that clr is also a variance stabilizing transformation. We're not recommending deseq2 or other VSTs at this time.
