### ISSUE TITLE
SpiecEasi is not compatible with Windows.

### ISSUE THREAD

**Issue by leimao** [zdk123/SpiecEasi#14]
When I was running your tutorial, it shows error:
Error in parallel::mclapply(1:rep.num, function(i) { : 
  'mc.cores' > 1 is not supported on Windows
I tried running the same tutorial on CentOS and there is no problem. 
I guess there are some problems of the parallel library you are using with Windows platform.

**Comment by zdk123** [comment]
Yes, this is not a spiec.easi issue, since parallel is not supported on Windows. Although I expect to have an alternative solution for this coming up in a new release, in the meantime I hope you can run the code in serial mode or on a *NIX system.

**Comment by FBakDK** [comment]
Hi,

To get around this, you can try:

 mclapply <- function (X, FUN, ..., mc.preschedule = TRUE, mc.set.seed = TRUE, 
                            mc.silent = FALSE, mc.cores = 1L, mc.cleanup = TRUE, mc.allow.recursive = TRUE) 
   {
        cores <- as.integer(mc.cores)
         if( .Platform$OS.type == "windows" )
            n.cores = 1
          }

As already mentioned it is not a specific issue with this package, and the solution was provided here:
https://github.com/thibautjombart/adegenet/issues/109
