### ISSUE TITLE
function 'sparseiCov' not found.  

### ISSUE THREAD

**Issue by suntzuisafterU** [zdk123/SpiecEasi#140]
R: 4.0.1
SpiecEasi: 1.0.7
OS: macOS 10.15.5

The following error is currently preventing me from using this library:

```
> SpiecEasi::spiec.easi(as.matrix(bfs_d[1:10]), method='glasso', lambda.min.ratio=0.01, nlambda=20, pulsar.params=list(rep.num=50))
Applying data transformations...
Selecting model with pulsar using stars...
Error in get(as.character(FUN), mode = "function", envir = envir) :
  object 'sparseiCov' of mode 'function' was not found
```

Loading the SpiecEasi library with `library(SpiecEasi)` resolves the above issue, but introduces a new one:
```
"_huge_hugeglasso" not resolved from current namespace (huge)
```
Which appears to be coming from:
```
SpiecEasi:::spiec.easi.default(...)
pulsar::pulsar(...)
pulsar:::.try_mclapply(...)
...
huge::huge.glasso(...)
```

This is a sporadic bug.  Currently it does not work, but yesterday it did with an identical library call.
It appears to have something to do with the way to enclosing environment is setup, but this should be independent of the libraries environment so I am not sure what is going on.

**Comment by zdk123** [comment]
Can you try upgrading to 1.1.0 by reinstalling the package?

**Comment by suntzuisafterU** [comment]
Reinstalled, seems to work.  Thanks!
