### ISSUE TITLE
Problem installing SpiecEasi - Pulsar package removed from cran repository on Aug 3, 2020

### ISSUE THREAD

**Issue by CynthiaBecker** [zdk123/SpiecEasi#141]
Hello, 

I am new to SpiecEasi. I am struggling to install SpiecEasi. I am running R 3.6.1 (Maybe I need to update?)
When I tried to install with `install_github("zdk123/SpiecEasi")` from the devtools package, it would not work. Initially it said there was no "pulsar" package available. I guess that package was removed from the CRAN repository on 2020-08-03. 
So I tried installing a previous version using the following:
```
pulsarurl <- "https://cran.r-project.org/src/contrib/Archive/pulsar/pulsar_0.3.6.tar.gz"
install.packages(pulsarurl, repos=NULL, type="source") #Worked
library(pulsar)
```
But then when I run `install_github("zdk123/SpiecEasi")`, it still doesn't work. My error message is the following:

Downloading GitHub repo zdk123/SpiecEasi@master
Skipping 1 packages not available: pulsar
✓  checking for file ‘/private/var/folders/5w/km45764s4s9_jrxnht5mdc040000gn/T/Rtmp3pa0qN/remotesfb0442ae70/zdk123-SpiecEasi-24f1075/DESCRIPTION’ ...
─  preparing ‘SpiecEasi’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘SpiecEasi/inst’
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘SpiecEasi_1.1.0.tar.gz’
   
* installing *source* package ‘SpiecEasi’ ...
** using staged installation
** libs
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c ADMM.cpp -o ADMM.o
clang: warning: no such sysroot directory: '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk' [-Wmissing-sysroot]
In file included from ADMM.cpp:1:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include/RcppArmadillo.h:31:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include/RcppArmadilloForward.h:26:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include/RcppCommon.h:29:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include/Rcpp/r/headers.h:67:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:304:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/math.h:300:15: fatal error: 'math.h' file not found
#include_next <math.h>
              ^~~~~~~~
1 error generated.
make: *** [ADMM.o] Error 1
ERROR: compilation failed for package ‘SpiecEasi’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/SpiecEasi’
installation of package ‘/var/folders/5w/km45764s4s9_jrxnht5mdc040000gn/T//Rtmp3pa0qN/filefb0707b0eaf/SpiecEasi_1.1.0.tar.gz’ had non-zero exit status

**Comment by zdk123** [comment]
pulsar was [briefly] removed from CRAN but it's back up. Please try again.

**Comment by CynthiaBecker** [comment]
Sorry to bring this back up, but I am still having trouble downloading Spiec-Easi. 

I have re-downloaded R a couple of times, both with the newest version (4.0.3) and older versions (3.6.3). When run the following code I end up with a *installation of package had non-zero exit status*
```
install.packages("pulsar")
install.packages("huge")
install.packages("MASS")
install.packages("devtools")

library(devtools)
install_github("zdk123/SpiecEasi")
```
It did prompt me to update some packages. I tried both with updating them, and without updating them, and I still was unable to install Spiec-Easi. I am a bit at a loss. This also happens when I try to install `seqgroup`, a package that uses SpiecEasi. 

The error message is printed here:
```
Downloading GitHub repo zdk123/SpiecEasi@HEAD
✓  checking for file ‘/private/var/folders/5w/km45764s4s9_jrxnht5mdc040000gn/T/RtmpFNaAg1/remotes12494b14661d/zdk123-SpiecEasi-24f1075/DESCRIPTION’ ...
─  preparing ‘SpiecEasi’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘SpiecEasi/inst’
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘SpiecEasi_1.1.0.tar.gz’
   
* installing *source* package ‘SpiecEasi’ ...
** using staged installation
** libs
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c ADMM.cpp -o ADMM.o
ADMM.cpp:25:9: warning: unused variable 'n' [-Wunused-variable]
    int n = A.n_cols;
        ^
ADMM.cpp:36:9: warning: unused variable 'l' [-Wunused-variable]
    int l = k;
        ^
ADMM.cpp:38:9: warning: unused variable 'n' [-Wunused-variable]
    int n = A.n_cols;
        ^
3 warnings generated.
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c matops.cpp -o matops.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c sqrtNewton.cpp -o sqrtNewton.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c svthresh.cpp -o svthresh.o
svthresh.cpp:11:9: warning: unused variable 'n' [-Wunused-variable]
    int n = A.n_cols;
        ^
1 warning generated.
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o SpiecEasi.so ADMM.o RcppExports.o matops.o sqrtNewton.o svthresh.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [SpiecEasi.so] Error 1
ERROR: compilation failed for package ‘SpiecEasi’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/SpiecEasi’
installation of package ‘/var/folders/5w/km45764s4s9_jrxnht5mdc040000gn/T//RtmpFNaAg1/file1249705c13b7/SpiecEasi_1.1.0.tar.gz’ had non-zero exit status
```

**Comment by zdk123** [comment]
This[ guide for installing fortran](https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/) on Mac
