### ISSUE TITLE
Thresholding edge weights?

### ISSUE THREAD

**Issue by lambertsbennett** [zdk123/SpiecEasi#143]
I've been creating networks using SpiecEasi and have been getting incredibly dense networks. In correlation-based approaches it is common to threshold links based on the correlation coefficient. Is there anything analogous in the SpiecEasi approach? I have seen your previous comment about setting the stars.thresh to select for sparser networks, but I was wondering if there was an alternative?

**Comment by zdk123** [comment]
Yes, you can also threshold the edges based on the number of subsamples in which the edge appeared. Check out the output of `getOptMerge`, which is a symmetric matrix similar to the adjacency matrix of the network but taking values between 0 and 1. You can be more confident about values closer to 1 - and I've seen good performance using a cutoff of .8 or so.

**Comment by lambertsbennett** [comment]
@zdk123 Great thanks for the tip!

**Comment by kiristern** [comment]
Hi @zdk123, could you explain how to filter the SpiecEasi output based on the `getOptMerge` threshold values? Thanks!

**Comment by Yuyushenghui** [comment]
Hey, is there a follow up on how to filter based on threshold value? I was wondering the same thing.
