### ISSUE TITLE
Cannot install SpiecEasi

### ISSUE THREAD

**Issue by Up4itat24** [zdk123/SpiecEasi#146]
Hello,

I am trying to install this package (on R v 3.6.1) and have been running into issues: 

When installing with the provided instructions

library(devtools)
install_github("zdk123/SpiecEasi")
library(SpiecEasi)

I get the folllowing errors: 

library(devtools)
Loading required package: usethis
> install_github("zdk123/SpiecEasi")
Downloading GitHub repo zdk123/SpiecEasi@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                           
2: CRAN packages only            
3: None                          
4: pulsar (0.3.6 -> 0.3.7) [CRAN]

Enter one or more numbers, or an empty line to skip updates:1
pulsar (0.3.6 -> 0.3.7) [CRAN]
Installing 1 packages: pulsar
Installing package into ‘/Users/maddiarnold/Library/R/3.6/library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/pulsar_0.3.7.tgz'
Content type 'application/x-gzip' length 428601 bytes (418 KB)
==================================================
downloaded 418 KB

The downloaded binary packages are in
	/var/folders/b4/rdk609g56m335qqjw6y0vkl40000gn/T//RtmpMabJdI/downloaded_packages
✓  checking for file ‘/private/var/folders/b4/rdk609g56m335qqjw6y0vkl40000gn/T/RtmpMabJdI/remotes53b249c4fb61/zdk123-SpiecEasi-24f1075/DESCRIPTION’ ...
─  preparing ‘SpiecEasi’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘SpiecEasi/inst’
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘SpiecEasi_1.1.0.tar.gz’
   
Installing package into ‘/Users/maddiarnold/Library/R/3.6/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘SpiecEasi’ ...
** using staged installation
** libs
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Users/maddiarnold/Library/R/3.6/library/Rcpp/include" -I"/Users/maddiarnold/Library/R/3.6/library/RcppArmadillo/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c ADMM.cpp -o ADMM.o
ADMM.cpp:25:9: warning: unused variable 'n' [-Wunused-variable]
    int n = A.n_cols;
        ^
ADMM.cpp:36:9: warning: unused variable 'l' [-Wunused-variable]
    int l = k;
        ^
ADMM.cpp:38:9: warning: unused variable 'n' [-Wunused-variable]
    int n = A.n_cols;
        ^
3 warnings generated.
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Users/maddiarnold/Library/R/3.6/library/Rcpp/include" -I"/Users/maddiarnold/Library/R/3.6/library/RcppArmadillo/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Users/maddiarnold/Library/R/3.6/library/Rcpp/include" -I"/Users/maddiarnold/Library/R/3.6/library/RcppArmadillo/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c matops.cpp -o matops.o
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Users/maddiarnold/Library/R/3.6/library/Rcpp/include" -I"/Users/maddiarnold/Library/R/3.6/library/RcppArmadillo/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c sqrtNewton.cpp -o sqrtNewton.o
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Users/maddiarnold/Library/R/3.6/library/Rcpp/include" -I"/Users/maddiarnold/Library/R/3.6/library/RcppArmadillo/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c svthresh.cpp -o svthresh.o
svthresh.cpp:11:9: warning: unused variable 'n' [-Wunused-variable]
    int n = A.n_cols;
        ^
1 warning generated.
clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o SpiecEasi.so ADMM.o RcppExports.o matops.o sqrtNewton.o svthresh.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [SpiecEasi.so] Error 1
ERROR: compilation failed for package ‘SpiecEasi’
* removing ‘/Users/maddiarnold/Library/R/3.6/library/SpiecEasi’
Error: Failed to install 'SpiecEasi' from GitHub:
  (converted from warning) installation of package ‘/var/folders/b4/rdk609g56m335qqjw6y0vkl40000gn/T//RtmpMabJdI/file53b24e984af8/SpiecEasi_1.1.0.tar.gz’ had non-zero exit status

any guidance would be greatly appreciated. Thank you!

**Comment by zdk123** [comment]
@Up4itat24 you are missing fortran binaries, probably.
