### ISSUE TITLE
Error: Failed to install 'SpiecEasi' from GitHub

### ISSUE THREAD

**Issue by jacobgmills** [zdk123/SpiecEasi#147]
Hi there,

Just trying to install SpiecEasi using the instructions. First there was an error installing igraph which I got around by sticking with the old version, but I still get the following error. 

See this screenshot for the errors. (https://user-images.githubusercontent.com/72478361/95275383-df9ebd80-088f-11eb-9e05-82cac2f69c7f.png)
)

Please help because I had this package recommended to me for microbial network analysis and would really like to use it.

**Comment by zdk123** [comment]
Looks like a missing fortran issue, (duplicate of #138) see my comment [there](https://github.com/zdk123/SpiecEasi/issues/138#issuecomment-660320574)

**Comment by jacobgmills** [comment]
Yes thank you, that seems to have worked! Cheers.
