### ISSUE TITLE
understandin co-occurence pattern.

### ISSUE THREAD

**Issue by kafker** [zdk123/SpiecEasi#148]
Dear all, 
After running SPIEC-EASI: 

`spiec = spiec.easi(as.matrix(t_data), method='glasso',sel.criterion = "stars",lambda.min.ratio=1e-3, nlambda=30, pulsar.params=pargs)`

I found that most of my clusters (see attached) are represented by low-abundant OTU detected only in one sample. My understanding is that none of these clusters are will be significant in respect to my experimental design (I have a total of three groups, each one represented by 8 samples) and therefore not interesting. Is my conclusion to naive or I am misunderstanding co-occurence networks?

I usually work with co-expression networks and, as sanity check, I look at clusters of genes with a co-expression pattern in agreement with my experimental variables

Thank you!
[Rplot.pdf](https://github.com/zdk123/SpiecEasi/files/5397356/Rplot.pdf)

**Comment by zdk123** [comment]
I can't answer specific questions without knowing more the data, but I would caution against interpreting co-occurrences between low-abundance OTUs (OTUs could exhibit spuriously correlated with sampling depth) and on small sample sizes (noise).

**Comment by kafker** [comment]
Dear Zachary,

You made yourself perfectly clear. That is what I have been looking for.

Thank you!

Andrea
