### ISSUE TITLE
Reproducing Result in the Publication

### ISSUE THREAD

**Issue by leimao** [zdk123/SpiecEasi#15]
Hi Zach,

I am recently practicing Spiec-Easi, and trying to reproduce the figure 4 i and j in your science paper "Helminth infection promotes colonization resistance via type 2 immunity" using your published method in the supplemental materials. However, the data I obtained for the plot using my own codes is slightly different to the data shown on your published figures. I was actually using the data downloaded from https://github.com/biocore/American-Gut, and I found these data are different to the data you claimed in your published paper. That might be one of the reasons why I got different results.
I wondered whether you can kindly send me the biom-formatted data you used in the paper? I may use these data to see whether I can reproduce the published result and further use Spiec-Easi in other projects. My email is dukeleimao@gmail.com. Thank you very much.

Best regards,
Lei Mao

**Comment by ParamjitGill** [comment]
I tried to install the package 'SpiecEasi' in R3.3.3 using 
> library(devtools)
> install_github("zdk123/SpiecEasi",  force=TRUE)
but got the error message
* installing *source* package 'SpiecEasi' ...
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'phyloseq'
ERROR: lazy loading failed for package 'SpiecEasi'
* removing 'C:/Program Files/R/R-3.3.3/library/SpiecEasi'
Error: Command failed (1)

**Comment by ParamjitGill** [comment]
Solved by 
source('http://bioconductor.org/biocLite.R')
biocLite('phyloseq')
