### ISSUE TITLE
Issue using spiec.easi with method='slr' for SpiecEasi version 1.1.0

### ISSUE THREAD

**Issue by LabouyrieMaeva** [zdk123/SpiecEasi#156]
Good afternoon, 

I am using R 4.0.2 and I wanted to reproduce the tutorial for latent variables available here [https://github.com/zdk123/SpiecEasi ]() after installing the latest version of SpiecEasi. And when I run the line:

`se2.slr.amgut <- SpiecEasi::spiec.easi(amgut2.filt.phy, method='slr', r=10, lambda.min.ratio=1e-2,
  nlambda=20, pulsar.params=list(rep.num=20, ncores=1))`

I get the following error message:

> Applying data transformations...
Selecting model with pulsar using stars...
Error in get(as.character(FUN), mode = "function", envir = envir) : 
  object 'sparseLowRankiCov' of mode 'function' was not found

However, a quick check of the package contents indicates the presence of the sparseLowRankiCov function. I tried manually to have the function read from the source code (from here directly [https://github.com/zdk123/SpiecEasi/blob/master/R/SparseLowRankICov.R](url)) but it requires calling the ADMM function and I can't compile it using Rcpp and sourceCpp() or equivalent. For this last try, the problem seems to be more related to Rtools itself even though it seems to be in the expected path. 

I also tried to install the branch of SpiecEasi ref = "lowrank" as suggested here [https://github.com/mblstamps/stamps2019/blob/master/STAMPS_Network_tutorial2019.R](url) but so far without success when using the slr method.

Could you help me on that please? 

Thank you very much,
Maëva

**Comment by zdk123** [comment]
Thanks for the bug report - I was able to reproduce this issue in R 4.0.2 I'll look into it!

**Comment by zdk123** [comment]
can you try the patch batch please? https://github.com/zdk123/SpiecEasi/tree/patch

**Comment by LabouyrieMaeva** [comment]
Thank you very much and sorry for my late reply! I've just tried the patch, and it seems to run until the end, but there is, with the example from the tutorial, the following message:

> Applying data transformations...
> Selecting model with pulsar using stars...
> warning: sqrtmat_sympd(): given matrix is not symmetric
> warning: sqrtmat_sympd(): given matrix is not symmetric
> warning: sqrtmat_sympd(): given matrix is not symmetric
> Fitting final estimate with slr...
> done

Is it expected because of the input data? The line producing it is:
`se2.slr.amgut <- spiec.easi(amgut2.filt.phy, method='slr', r=10, lambda.min.ratio=1e-2,
                            nlambda=20, pulsar.params=list(rep.num=20, ncores=1))`

Thank you,
Maëva

**Comment by LabouyrieMaeva** [comment]
Good morning! I just have a quick question about the previous output following the patch for the slr-method with spieceasi(): despite the message displayed concerning the sqrtmat_sympd(), is the object provided by the function usable as such for further analysis or this warning indicates that it is not?

Thank you very much,
Best,
Maëva
