### ISSUE TITLE
Does the clr transformation solve the problem of variable sampling effort between samples?

### ISSUE THREAD

**Issue by paoluxe** [zdk123/SpiecEasi#163]
Hello, 

I am currently a master trainee and I am interested in using spiec-easi to infer the microbial network.
In other posts, I read that you advise to put non rarefied data in the function. If my interpretation is correct, rarefaction is used to 1) scale all samples to the same level, i.e. all samples have the same total number of reads and 2) ensure that the sampling effort is satisfactory and is the same for all samples, i.e. looking for the rarefaction curve to reach a plateau to "cut off". 

I can see how the clr transformation solves 1), but I cannot see how it solves 2).

Can you please tell me more?

Sincerely

Paola

**Comment by zdk123** [comment]
It's not the clr transform that achieves sample scaling but total sum normalization, e.g. scaling each count by the total observed counts in the sample. Rarefaction curves (repeated rarifying at different levels to check sampling effort) is not the same procedure as rarefaction (rarifying once at the minimum-observed sampling depth).
