### ISSUE TITLE
Installing SpiecEasi in HPC server

### ISSUE THREAD

**Issue by tcrispino13** [zdk123/SpiecEasi#169]
Hi could anyone help me, I am encountering problems in installing the package in server. I am currently running this R script under a bash script 

.libPaths( c( "~/scratch1/theresa.crispino/Rlib" , .libPaths() ) )
r = getOption("repos")
r["CRAN"] = "https://cran.stat.upd.edu.ph/"
options(repos = r)
install.packages("~/scratch1/theresa.crispino/script/SpiecEasi-1.1.0.zip", type="source", repos=NULL)
.libPaths()

I downloaded the tar.gz and zip files when errors occurred during the installation of devtools and then opt to just install these files but unfortunately I keep on having this error message:

Warning: invalid package â€˜/SpiecEasi-1.1.0.zipâ€™
Error: ERROR: no packages specified
Warning message:
In install.packages("~/SpiecEasi-1.1.0.zip",  :
  installation of package â€˜/SpiecEasi-1.1.0.zipâ€™ had non-zero exit status

Thanks for your answers!

**Comment by zdk123** [comment]
I was able to run:
```sh
wget https://github.com/zdk123/SpiecEasi/archive/refs/tags/v1.1.0.tar.gz -O SpiecEasi_v1.1.0.tar.gz
Rscript -e "install.packages(\"SpiecEasi_v1.1.0.tar.gz\", repos=NULL, type=\"source\")"
```

Can you provide a more detailed error message and system specs if that fails?

**Comment by tcrispino13** [comment]
Thanks for this. I will try it and update you! Thanks again!

**Comment by tcrispino13** [comment]
Hello, It was a success! Thank you for your help!
