### ISSUE TITLE
Interpretation of p-values from pval.sparccboot

### ISSUE THREAD

**Issue by hoangtt1989** [zdk123/SpiecEasi#17]
After running pval.sparccboot on a sparccboot object, the `pvals` output is a vector which seems to contain the p values for either the upper or lower triangular part of the SparCC correlation matrix. My question is how do we determine which entries of the correlation matrix correspond to the entries given by `pvals`, so we can determine the significant correlations.

**Comment by zdk123** [comment]
The values are the upper triangle. You can recover the symmetric matrix with something like

```
X <- diag(p) 
X[upper.tri(X, diag=FALSE)] <- p.vals
X <- X + t(X)
```

**Comment by iuh-z** [comment]
Hi, zdk123! After running the sparccboot and pval.sparccboot on the 26 taxa, I got a vector containing 325 of p.value. How can I match the p.value to the correlation of the 26 taxa? Could I get a 26*26 matrix for the p.value?

**Comment by cramjaco** [comment]
Just to clarify. In the example above. `p` would be a vector of ones the length of the number of taxa you are comparing. So in @iuh-z 's example, you could say p <- rep(1, 26), and then run @zdk123 's example code and then you'd have the right sized matrix. Then you'd want to copy over the rownames and the columnnames from your original data.
