### ISSUE TITLE
Cannot compile SpiecEasi due to Armadillo error

### ISSUE THREAD

**Issue by ZhikWang** [zdk123/SpiecEasi#183]
Dear all,

Thanks a lot for all information. However, I'm still having this "ERROR: compilation failed for package ‘SpiecEasi’" when installing the package in Rstudio (R 4.0.1). I've tried to install Rcpp and RcppArmadillo before the installation of SpiecEasi, but still the error. Do you know how to solve this issue? Thanks in advance!

----------------------------------------------------------------------------------------
> install_github("zdk123/SpiecEasi")
Downloading GitHub repo zdk123/SpiecEasi@HEAD
✓  checking for file ‘/tmp/RtmptozNT6/remotes2a27193305fb0d/zdk123-SpiecEasi-ff528b2/DESCRIPTION’ (642ms)
─  preparing ‘SpiecEasi’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘SpiecEasi/inst’
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘SpiecEasi_1.1.1.tar.gz’
   
Installing package into ‘my library’
(as ‘lib’ is unspecified)
* installing *source* package ‘SpiecEasi’ ...
** using staged installation
** libs
g++ -std=gnu++11 -I"/opt/R/4.0.1/lib/R/include" -DNDEBUG  -I'/my library/Rcpp/include' -I'my library/RcppArmadillo/include' -I/usr/local/include   -fpic  -g -O2  -c ADMM.cpp -o ADMM.o
ADMM.cpp: In function ‘Rcpp::List ADMM(const mat&, const double&, arma::mat&, arma::mat&, arma::mat&, double, int, double, const double&, const double&, const int&, const double&, const double&, const double&, bool)’:
ADMM.cpp:193:28: error: no match for ‘operator=’ (operand types are ‘arma::subview_cols<double>’ and ‘arma::sp_mat’ {aka ‘arma::SpMat<double>’})
  193 |       X.cols(n  , n*2-1) = S;
      |                            ^
In file included from /my library/RcppArmadillo/include/armadillo:617,
                 from /my library/RcppArmadillo/include/RcppArmadilloForward.h:48,
                 from /my library/RcppArmadillo/include/RcppArmadillo.h:29,
                 from ADMM.cpp:1:
/my library/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3940:1: note: candidate: ‘void arma::subview_cols<eT>::operator=(const arma::subview<eT>&) [with eT = double]’
 3940 | subview_cols<eT>::operator=(const subview<eT>& X)
      | ^~~~~~~~~~~~~~~~
/my library/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3940:48: note:   no known conversion for argument 1 from ‘arma::sp_mat’ {aka ‘arma::SpMat<double>’} to ‘const arma::subview<double>&’
 3940 | subview_cols<eT>::operator=(const subview<eT>& X)
      |                             ~~~~~~~~~~~~~~~~~~~^
/my library/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3952:1: note: candidate: ‘void arma::subview_cols<eT>::operator=(const arma::subview_cols<eT>&) [with eT = double]’
 3952 | subview_cols<eT>::operator=(const subview_cols<eT>& X)
      | ^~~~~~~~~~~~~~~~
/my library/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3952:53: note:   no known conversion for argument 1 from ‘arma::sp_mat’ {aka ‘arma::SpMat<double>’} to ‘const arma::subview_cols<double>&’
 3952 | subview_cols<eT>::operator=(const subview_cols<eT>& X)
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~^
/my library/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3988:1: note: candidate: ‘void arma::subview_cols<eT>::operator=(eT) [with eT = double]’
 3988 | subview_cols<eT>::operator=(const eT val)
      | ^~~~~~~~~~~~~~~~
/my library/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3988:38: note:   no known conversion for argument 1 from ‘arma::sp_mat’ {aka ‘arma::SpMat<double>’} to ‘double’
 3988 | subview_cols<eT>::operator=(const eT val)
      |                             ~~~~~~~~~^~~
/my library/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3964:1: note: candidate: ‘void arma::subview_cols<eT>::operator=(const std::initializer_list<_Tp>&) [with eT = double]’
 3964 | subview_cols<eT>::operator=(const std::initializer_list<eT>& list)
      | ^~~~~~~~~~~~~~~~
/my library/4.0/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3964:62: note:   no known conversion for argument 1 from ‘arma::sp_mat’ {aka ‘arma::SpMat<double>’} to ‘const std::initializer_list<double>&’
 3964 | subview_cols<eT>::operator=(const std::initializer_list<eT>& list)
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/my library/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3976:1: note: candidate: ‘void arma::subview_cols<eT>::operator=(const std::initializer_list<std::initializer_list<_Tp> >&) [with eT = double]’
 3976 | subview_cols<eT>::operator=(const std::initializer_list< std::initializer_list<eT> >& list)
      | ^~~~~~~~~~~~~~~~
/my library/RcppArmadillo/include/armadillo_bits/subview_meat.hpp:3976:87: note:   no known conversion for argument 1 from ‘arma::sp_mat’ {aka ‘arma::SpMat<double>’} to ‘const std::initializer_list<std::initializer_list<double> >&’
 3976 | subview_cols<eT>::operator=(const std::initializer_list< std::initializer_list<eT> >& list)
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
In file included from /my library/RcppArmadillo/include/armadillo:167,
                 from /my library/RcppArmadillo/include/RcppArmadilloForward.h:48,
                 from /my library/RcppArmadillo/include/RcppArmadillo.h:29,
                 from ADMM.cpp:1:
/my library/RcppArmadillo/include/armadillo_bits/subview_bones.hpp:476:15: note: candidate: ‘template<class T1> void arma::subview_cols<eT>::operator=(const arma::Base<eT, T1>&) [with T1 = T1; eT = double]’
  476 |   inline void operator= (const Base<eT,T1>& x);
      |               ^~~~~~~~
/my library/RcppArmadillo/include/armadillo_bits/subview_bones.hpp:476:15: note:   template argument deduction/substitution failed:
ADMM.cpp:193:28: note:   ‘arma::sp_mat’ {aka ‘arma::SpMat<double>’} is not derived from ‘const arma::Base<double, T1>’
  193 |       X.cols(n  , n*2-1) = S;
      |                            ^
In file included from /my library/RcppArmadillo/include/armadillo:167,
                 from /my library/RcppArmadillo/include/RcppArmadilloForward.h:48,
                 from /my library/RcppArmadillo/include/RcppArmadillo.h:29,
                 from ADMM.cpp:1:
/my library/RcppArmadillo/include/armadillo_bits/subview_bones.hpp:479:94: note: candidate: ‘template<class T1, class gen_type> typename arma::enable_if2<arma::is_same_type<typename T1::elem_type, eT>::value, void>::result arma::subview_cols<eT>::operator=(const arma::Gen<T1, gen_type>&) [with T1 = T1; gen_type = gen_type; eT = double]’
  479 |   inline typename enable_if2< is_same_type<typename T1::elem_type, eT>::value, void>::result operator=(const Gen<T1,gen_type>& x);
      |                                                                                              ^~~~~~~~
/my library/RcppArmadillo/include/armadillo_bits/subview_bones.hpp:479:94: note:   template argument deduction/substitution failed:
ADMM.cpp:193:28: note:   ‘arma::sp_mat’ {aka ‘arma::SpMat<double>’} is not derived from ‘const arma::Gen<T1, gen_type>’
  193 |       X.cols(n  , n*2-1) = S;
      |                            ^
make: *** [/opt/R/4.0.1/lib/R/etc/Makeconf:176: ADMM.o] Error 1
ERROR: compilation failed for package ‘SpiecEasi’
* removing ‘my library/SpiecEasi’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmptozNT6/file2a27197ec05cc8/SpiecEasi_1.1.1.tar.gz’ had non-zero exit status

**Comment by taoke1** [comment]
I meet similar problem when installing SpiecEasi by Rstudio on my windows, would be appreciate if someone have suggestions

**Comment by gim4** [comment]
I am also having a similar problem where I keep getting a 'non zero exit status' warning message as well.

**Comment by zdk123** [comment]
I can replicate this issue - looks like a change in assigning data to views in Armadillo matrix. It will take a few days to fix.

**Comment by gim4** [comment]
> @gim4 @ZhikWang @taoke1 Can you try installing from the `patchsrc` branch please?
> 
> ```r
> devtools::install_github("zdk123/SpiecEasi", ref="patchsrc")
> ```

Brilliant, that successfully installed now! Thank you!
