### ISSUE TITLE
Cann't install SpiecEasi

### ISSUE THREAD

**Issue by JingjingChan** [zdk123/SpiecEasi#191]
> devtools::install_github("zdk123/SpiecEasi", ref="patchsrc")
Downloading GitHub repo zdk123/SpiecEasi@patchsrc
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                           
2: CRAN packages only            
3: None                          
4: igraph (1.2.8 -> 1.2.9) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 4
igraph (1.2.8 -> 1.2.9) [CRAN]
Installing 1 packages: igraph
Warning: 正在使用‘igraph’这个程序包，因此不会被安装
√  checking for file 'C:\Users\Lenovo\AppData\Local\Temp\RtmpY7XEN9\remotes29a0ad0216c\zdk123-SpiecEasi-ca7ebe9/DESCRIPTION' ...
-  preparing 'SpiecEasi':
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
   Removed empty directory 'SpiecEasi/inst'
-  looking to see if a 'data/datalist' file should be added
-  building 'SpiecEasi_1.1.2.tar.gz'
   
* installing *source* package 'SpiecEasi' ...
** using staged installation
** libs

*** arch - i386
"c:/rtools40/mingw32/bin/"g++  -std=gnu++11 -I"D:/Program Files/R/R-4.1.2/include" -DNDEBUG  -I'D:/Program Files/R/R-4.1.2/library/Rcpp/include' -I'D:/Program Files/R/R-4.1.2/library/RcppArmadillo/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c ADMM.cpp -o ADMM.o
sh: line 1: c:/rtools40/mingw32/bin/g++: No such file or directory
make: *** [D:/Program Files/R/R-4.1.2/etc/i386/Makeconf:245: ADMM.o] Error 127
ERROR: compilation failed for package 'SpiecEasi'
* removing 'D:/Program Files/R/R-4.1.2/library/SpiecEasi'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/Lenovo/AppData/Local/Temp/RtmpY7XEN9/file29a031424f69/SpiecEasi_1.1.2.tar.gz’ had non-zero exit status

**Comment by zdk123** [comment]
This is a windows machine?  You may need Rtools https://cran.r-project.org/bin/windows/Rtools/rtools40.html
