### ISSUE TITLE
Number of nodes exceeds input dataset

### ISSUE THREAD

**Issue by susheelbhanu** [zdk123/SpiecEasi#192]
Hi, 

I'm running SpiecEasi as follows:
```
SE <- spiec.easi(list(mat_prok, mat_euk), method = "glasso", sel.criterion='bstars', nlambda = 10, lambda.min.ratio = 1e-2, pulsar.select=TRUE, pulsar.params=pargs)
```

The two input files combined have 537 OTUs

Interestingly enough, I'm noticing the that the number of `V` or `nodes` in my `SE$est$data` is showing up as 921 nodes. Is this accurate or am I to be looking at the data in another object?

Thank you!

**Comment by zdk123** [comment]
I'm not sure how you are calculating the number of nodes here, but the number of OTUs should match `ncol(SE$est$data)` and  `ncol(mat_prok) + ncol(mat_euk)`. Is this not what you observe?

**Comment by susheelbhanu** [comment]
Hey @zdk123 

I have 421 in mat_prok and 116 in mat_euk, but ncol(SE$est$data) is showing 921. Rerunning from scratch to confirm. Will keep you posted. 

Thank you!

**Comment by zdk123** [comment]
and just to rule out transpose-related bugs, what is `nrow` for the matrices?

**Comment by susheelbhanu** [comment]
38 each, with matched samples

**Comment by zdk123** [comment]
could you send me your data attached to an email? I can't seem reproduce this error.

**Comment by susheelbhanu** [comment]
Terribly sorry for the late response. I reran everything over the holidays. Just so you and others may be aware, I was using a `snakemake` workflow to run the Rscripts on several samples. Turns out that one of the older `.rds` files stuck around, which was being read in and causing this issue. 

A clean run gives me the expected number of OTUs. Thank you for the help with this!
