### ISSUE TITLE
Handle edge based on edge confidence 

### ISSUE THREAD

**Issue by flavien-maucourt** [zdk123/SpiecEasi#195]
Hi Zach, 

According to this previous topic : https://github.com/zdk123/SpiecEasi/issues/176 , I'm trying to do the same thing with my data. I have 3000 OTUs for (only...) 20 samples. the spiec.easi object is calculated as follow : 

spiec.out.phy=spiec.easi(phyloseqobj.f,
                         method="mb", 
                         sel.criterion = 'stars',
                         lambda.min.ratio = 1e-4,
                         nlambda = 30,
                         icov.select.params=list(rep.num=15, ncores=14)
)

I got a good stability of 0.049 and I'm able to plot a very dense graph of this calcul. Because of the previous comments and answers I'd like to try the edge-based confidence filter, as suggested by you. So this is what i did : 

1. Got the spiec.easi object with the previous code 
2. Got the edge-based confidence : 

semerge <- getOptMerge(spiec.out.phy)

3. Do the filtering : 

senet <- getRefit(spiec.out.phy) * semerge
semerge_filt <- senet[senet >= 0.8]

But i got this error : 

![image](https://user-images.githubusercontent.com/95645731/146774914-b629e1bc-605b-4467-b7f4-49647c844e79.png)

So i tried something else : 

semerge <- getOptMerge(spiec.out.phy)>=0.8
senet <- getRefit(spiec.out.phy)*semerge
spiec.graph.phy <- adj2igraph(senet, vertex.attr=list(name=taxa_names(phyloseqobj.f)))
fig <- plot_network(spiec.graph.phy,phyloseqobj.f, type='taxa', color="Domain", label = NA)
fig

I got a graph :

![image](https://user-images.githubusercontent.com/95645731/146763459-92718cab-b284-4665-857d-542d2ac992ce.png)

But I'm pretty sure that is not correct ! ^^ 

Could you guide me ? 

Last one thing, (If it's not the good place to ask it let me know) these data came from a polluted soil and sample are classified as polluted or not polluted (this is referenced into the metadata of my phyloseq object). How could I sort/plot/read my network based on this information ? 

Thank you in advance for your answer and have a good day.

_Originally posted by @flavien-maucourt in https://github.com/zdk123/SpiecEasi/issues/176#issuecomment-997862496_

**Comment by flavien-maucourt** [comment]
I find out the drop0 fonction and using it like following : 

threshold <- 0.8
senet <- drop0(senet, tol = threshold)

all edges with confidence < 0.8 are discard but i got this plot : 

![image](https://user-images.githubusercontent.com/95645731/147118307-ce68ed6b-bd2f-4c9d-9e53-1c7293f403ea.png)

is this relevant ? 

I tried with lower threshold and it seems to be a matter of scale. Nodes without edges are very distant and nodes with edges a concentrated on the bottom left corner.

**Comment by zdk123** [comment]
The original 'error' is a pretty innocuous warning about subsampling sparse matrices. `drop0`, as you found, or converting to a dense matrix should resolve it.

The boring answer for your second point is that I don't think phyloseq's plot_network function works very well. Perhaps switch to another package or a GUI program such as cytoscape for plotting graphs.

**Comment by flavien-maucourt** [comment]
Thanks for your answer ! 

As you suggested, I tried another plotting method and found out that my plotting was due to fruchterman reingold layout. With another layout it's possible to obtain something more readable. Whatever the layout metrics are the same and that is important !
