### ISSUE TITLE
Obtaining Edge Weight Matrix in SLR Method

### ISSUE THREAD

**Issue by erfanshekarriz** [zdk123/SpiecEasi#198]
Dear Zachary, 

Hope all is well. I've submitted this question previously, but it was closed without being answered so I wanted to inquire again in case you might have missed it! 

I wanted to ask about the newly implemented SLR method with sparse low-rank matrices. Specifically, **How to Obtain Edge Weights with SLR**? What are the equivalents of getOptCov (Glasso) and getOptBeta (MB) for the newly implemented SLR method?

My publication is nearly ready, but I wanted to provide additional edge weight information to give a complete picture. Your help is super appreciated. 

Best, 

Erfan SHEKARRIZ

**Comment by zdk123** [comment]
Thanks for the report - I actually still need to expand getters for the slr case.

A work around for the [inverse] covariance is:
```r
se.icov <- se$select$est$icov[[getOptInd(se)]]
se.cov <- solve(se.icov)
```
where `se` is the output from spiec.easi.

**Comment by erfanshekarriz** [comment]
> Thanks for the report - I actually still need to expand getters for the slr case.
> 
> A work around for the [inverse] covariance is:
> 
> ```r
> se.icov <- se$select$est$icov[[getOptInd(se)]]
> se.cov <- solve(se.icov)
> ```
> 
> where `se` is the output from spiec.easi.

Dear Zachary, 

Many thanks. This is exactly what I was looking for. The SLR method is of great value.

Best

Erfan

**Comment by erfanshekarriz** [comment]
Dear Zachary, 

When converting the covariance matrix to a graph object using iGraph's graph.adjacency() function, you obtain many more edges than the original unweighted network (I'm not exactly sure why).

To resolve this issue, I've implemented my own code that I thought to share with others if they would like to create a weighted network graph. 

`
# create igraph object 
se.igraph <- adj2igraph(getRefit(se),  vertex.attr=(list(name=taxa_names(physeq))))

# obtain covariance matrix 
se.icov <- se$select$est$icov[[getOptInd(se)]]
se.cov <- solve(se.icov)

rownames(se.cov) <- colnames(otu_table(physeq))
colnames(se.cov) <- colnames(otu_table(physeq))
se.cov.names <- colnames(otu_table(physeq))

se.weighted <- graph.adjacency(se.cov, mode = "undirected",
                                       weighted = TRUE, diag = FALSE)


# find overlap between the new se.weighted graph and previous se.igraph
# function adapted from  cjolley on StackOverflow to get matching edges between two graphs

se.weighted.matching <- se.weighted

matching_edge <- function(g1,e,g2) {
  # given an edge e in g1, return the corresponding edge in g2
  name1 <- V(g1)[get.edges(g1,e)[1,1]]$name
  name2 <- V(g1)[get.edges(g1,e)[1,2]]$name
  E(g2)[get.edge.ids(g2,c(name1,name2))]
}

for (e in E(se.igraph)) {
  eg <- matching_edge(se.igraph, e, se.weighted.matching )
  E(se.weighted.matching )[eg]$weight <- eg$weight
  E(se.weighted.matching )[eg]$igraph <- "igraph" #new attribute to label matching edges
}

se.weighted.matching <- delete_edges(se.weighted.matching, which(is.na(E(se.weighted.matching)$igraph)))


# check if matching was done correctly 
E(se.graph) == E(se.weighted.matching)

`

Hope that helps!

Best, 

Erfan

**Comment by zdk123** [comment]
This can actually be done more simply by operating on the adjacency matrix directly:

```r
se.weighted <- graph.adjacency(se.cov*getRefit(se), mode = "undirected", weighted = TRUE, diag = FALSE)
```
