### ISSUE TITLE
map_levels issue using spieceasi and igraph

### ISSUE THREAD

**Issue by RomGallet** [zdk123/SpiecEasi#199]
Hi Zachary, 
I'm currently trying to draw interaction networks using phyloseq, spieceasi and igraph, and I can't figure out how to make the map_levels function to work.
What I want to do, is to use the phylogenetic information so that nodes belonging to the same family will have the same color in my interaction network.
To do so, I believe I need to use the "map_levels" function.
Here is the code I was first using:

_phyla1 <- map_levels(colnames(otu1), from = "Phylum", to = "Genus", APOsCor %>% tax_table() %>% as("matrix") %>% data.frame())_

where APOsCor is a phyloseq object, and _otu1 <- t(otu_table(APOsCor)@.Data)_ .

But when I take a look at phyla1, this is what I get:

    _phyla1_
$OTU_122
character(0)

$OTU_586
character(0)

$OTU_29
character(0)
(...)

Why character(0)??

Of course, when I try to use phyla1 to plot the network, it won't work.
_td.net1 %v% "Phylum" <- phyla1
p1 <- ggnet2(td.net1, node.color = "Phylum", label = TRUE, node.size = "nodesize", label.size = 2, edge.color = "color") + guides(color=guide_legend(title="Phylum"), size = FALSE) + mycolors_
Error in $<-.data.frame(*tmp*, "color", value = character(0)) :
replacement table has 0 lines, replaced table has 830 (I translated this message from French to English).

Do you have any idea about what the problem is?
Thank you in advance.
Best regards,
Romain

**Comment by zdk123** [comment]
I am unfamiliar with that function. Feel free to reopen this issue if you still want a second set of eyes on it.
