### ISSUE TITLE
Running spiec.easi on a OTU table without phyloseq

### ISSUE THREAD

**Issue by mianfermar** [zdk123/SpiecEasi#20]
Hi there!

I am trying to run 'spiec.easi' and plot the results just following the pipeline from 9th of August 2016 but reading an OTU table generated by me without using any 'phyloseq' object (just the 'plain' table).
I do the following:

    library(devtools)
    library(SpiecEasi)
    library(igraph)
    library(phyloseq) #supposing not to be necessary

    tabla <- read.csv("tabla.csv")

    se.tabla <- spiec.easi(tabla, method='mb', lambda.min.ratio=1e-2, nlambda=20,   icov.select.params=list(rep.num=20))

And I get this message: 

    Error in seq.default(log(lambda.max), log(lambda.min), length = nlambda) : 
    'from' must be a finite number
    In addition: Warning message:
    In Ops.factor(left, right) : ‘+’ not meaningful for factors

So the pipeline stops
Is it possible to do what I need? Am I making any mistake? 

The OTU table file ("tabla.csv") looks as follows:

    P,D3_SF,D3_20,D3_80,D6_SF,D6_20,D6_80,D8_SF,D8_20,D8_80,D10_50
    GCSP_PSEFS,1,1,1,1,1,0,1,1,1,1
    EFTU_PSEFS,1,1,1,1,1,1,1,1,0,0
    PNP_PSEFS,1,1,1,0,1,1,1,1,1,1
    EFG_PSEFS,1,1,1,1,1,0,1,1,1,1
    ...

Thanks a lot

**Comment by zdk123** [comment]
It should be no problem to do this. The error is arising from the automatic
detection of lambda.max, which likely is not a number or infinite. This is
just the max abs value of the correlation matrix from the data. Try
converting the data.frame to a numeric matrix (possibly R is treating your
columns as factors and not numerics) and make sure that the OTUs are on the
column margins, and not rows.

Please report if this solves the issue.

**Comment by mianfermar** [comment]
I'll try this today, sorry for the delay, but I've been out of office for a couple of days.

I'll let you know step by step.

Thanks a lot

**Comment by mianfermar** [comment]
I have tried the following from a script I have for diversity analyses in vegan:

    rownames(tabla) <- tabla[,1]	
    tabla <- tabla[,-1] 
    tabla <- t(tabla)

And then:
    se.tabla <- spiec.easi(tabla, method='mb', lambda.min.ratio=1e-2, nlambda=20, icov.select.params=list(rep.num=20))

And the analysis seems to be running, although it will take a while to end (>2000 OTUs)

Seems correct what I've done?

**Comment by zdk123** [comment]
Looks correct, though you may have issues with so many OTUs especially if you are not parallelizing StARS. Please contact me via email, and I can give you more specific advice.
