### ISSUE TITLE
still support older version of SpiecEasi?

### ISSUE THREAD

**Issue by marwa38** [zdk123/SpiecEasi#203]
Hi there .. I am trying to reproduce this tutorial https://mibwurrepo.github.io/Microbial-bioinformatics-introductory-course-Material-2018/inference-of-microbial-ecological-networks.html
I know that you recommend the latest version of SpiecEasi but I can see the difference between the version used in this tutorial and the latest release (version). Do you still support  SpiecEasi_1.0.7 version?

Many thanks

**Comment by zdk123** [comment]
That's not my tutorial, so I can't speak to what is/is not compatible with the latest version. I try to get major versions backwards compatible so I would be interested in knowing if anything in the latest release is breaking.

The source code for [v1.0.7 is on the release page](https://github.com/zdk123/SpiecEasi/releases/tag/v1.0.7) of this github and on bioconda as well.
