### ISSUE TITLE
node size according to abundance count or degree frequency

### ISSUE THREAD

**Issue by Joyce2896** [zdk123/SpiecEasi#209]
Hi, 

May I know is it possible to have the node size adjust to abundance count or degree frequency? Would like to have that function (or possible if you can tweak the code a little for now). As of current, all the nodes are in similar size. Though I can change that by importing the matrix to cytoscape, but would appreciate if is doable using R. 

Thank you. 
regards, 
Joyce

**Comment by zdk123** [comment]
See the igraph plotting docs. Outside the scope of this package.
