### ISSUE TITLE
Error in Installing SpiecEasi package

### ISSUE THREAD

**Issue by DzungNguyen181** [zdk123/SpiecEasi#211]
Hi, 
I've tried to install the package SpiecEasi using the command lines:
library(devtools)
install_github("zdk123/SpiecEasi")

but keep running into this error:

![image](https://user-images.githubusercontent.com/102470900/172065479-fe459ce2-48ca-4c7a-97d7-24dae21c52fd.png)

I’m struggling to solve this problem although I already searched for the solution via internet.
I've tried to consult my teacher and he told me:
"This kind of problem is specific to your computer, and it happens because of some underlying C++ code is probably missing or cannot be found. Because this happens due to the way the package is programmed, the only way to solve this is to contact the authors of the package…"

Could someone help me with this, please?!
Look forward to your help and thank you already.

**Comment by zdk123** [comment]
Windows users need Rtools:
https://cran.r-project.org/bin/windows/Rtools/

**Comment by DzungNguyen181** [comment]
> Windows users need Rtools to compile code: https://cran.r-project.org/bin/windows/Rtools/

Hello, thank you so much for the suggestion. I successfully installed the package.
