### ISSUE TITLE
Failed to install 'SpiecEasi' from GitHub

### ISSUE THREAD

**Issue by Ruser111** [zdk123/SpiecEasi#215]
Hello,

I have been trying to install 'SpiecEasi' but without success. I have installed all the required R packages and Rtools 4.2 as well. Thank you for your help!

library(devtools)
Loading required package: usethis
install_github("zdk123/SpiecEasi")
Downloading GitHub repo zdk123/SpiecEasi@HEAD
Error: Failed to install 'SpiecEasi' from GitHub:
Multiple results for CXXFLAGS found, something is wrong.FALSE

Below is my R specs:
platform: x86_64-w64-mingw32/x64 (64-bit) 
R version: 4.2.1

**Comment by Ruser111** [comment]
Just in case other folks had similar issues with this...

I finally find a way to make it work. I ended up installing SpiecEasi using source code directly.

First, do not use R 4.2.1; use R 4.1.2 (or earlier) instead.
Second, install Rtools 4.0 [https://cran.r-project.org/bin/windows/Rtools/]. Make sure to name the folder 'Rtools' instead of 'rtools40' (default name) when you install Rtools in your computer. 
Third, within the Rtools folder, rename the folder 'mingw64' with 'mingw_64' (or rename mingw32 with mingw_32 if you have a 32-bit system).

It appears the path is hard coded in the installation file, so you have to rename the folder manually.

**Comment by zdk123** [comment]
Wow this is a wild bug. Thanks for figuring out the fix as well. Is this a known Rcpp /Rtools issue?

**Comment by Ruser111** [comment]
> Wow this is a wild bug. Thanks for figuring out the fix as well. Is this a known Rcpp /Rtools issue?

Yes I think so. I was inspired by the discussion here [https://stackoverflow.com/questions/39090983/rcpp-rtools-installed-but-error-message-g-not-found](url)
