### ISSUE TITLE
Query: Applying SpiecEasi network building method at genus or higher taxonomic level

### ISSUE THREAD

**Issue by wasimbt** [zdk123/SpiecEasi#216]
Hi, 

Thank you for creating SPIEC-EASI for robust network analysis. Could you please let me know if it is possible to apply the method at genus or higher taxa levels (i am anyway making the network at ASV level)?  

Thank you in advance!

Best regards, 
Wasim

**Comment by zdk123** [comment]
Yep that's a perfectly valid use case. In the compositional data analysis literature, the summation of component counts is known as an "amalgam". I've applied SpiecEasi to aggregate counts myself.

**Comment by wasimbt** [comment]
Many thanks for your answer!

Just one more thing, is there a way, I can get the edge weight list along with respective nodes in a file.

Best, Wasim

**Comment by zdk123** [comment]
Yes, there is example code for getting edge lists in the readme: https://github.com/zdk123/SpiecEasi#analysis-of-american-gut-data

**Comment by wasimbt** [comment]
Thanks alot, I will try such and let you know. 

I am closing the issue for now. 

Best, Wasim
