### ISSUE TITLE
Error installing on RStudio Cloud

### ISSUE THREAD

**Issue by SarithaKodikara** [zdk123/SpiecEasi#218]
I've been trying to install this package on the RStudio cloud but have been getting the following error.
 Any help would be appreciated.

![Screen Shot 2022-08-23 at 12 43 42 pm](https://user-images.githubusercontent.com/64136603/186057772-ffb4b629-80f5-4906-8b80-b441083bb7c5.png)

**Comment by zdk123** [comment]
I can replicate this on the free version of RStudio cloud... it looks like the memory utilization goes up to 100% during package compiling and then it crashes. Getting the same issue on some of the larger, dependent packages so I don't think there's an easy workaround... but maybe compiling locally (or the prebuilt linux binaries via conda) and transfering to the cloud would work.
