### ISSUE TITLE
package ‘SpiecEasi’ is not available (for R version 3.4.0)

### ISSUE THREAD

**Issue by Steffi17** [zdk123/SpiecEasi#22]
Hi,
I am trying to instal SpiecEasi but but get the following error:
package ‘SpiecEasi’ is not available (for R version 3.4.0)
How can it be fixed without reinstalling an older R version?
Thanks a lot for your help and looking forward to using your tool :)

**Comment by zdk123** [comment]
SpiecEasi is not on CRAN. See the Readme on this repo, thanks.
