### ISSUE TITLE
Error using negative values from SpiecEasi with Fruchterman-Reingold layout

### ISSUE THREAD

**Issue by paddyhooper** [zdk123/SpiecEasi#221]
Hi @zdk123 ,

Thank you for this amazing resource! I am hoping to look at network interactions in my 18S dataset within phyloseq. 

My script is:

net.c<- spiec.easi(otu.c, method='mb', icov.select.params=list(rep.num=999)) 

n.c <- symBeta(getOptBeta(net.c_18S))
n.c

#Add names to IDs and abundance values to vertex (nodes)
colnames(n.c) <- rownames(n.c) <- colnames(otu.c)
vsize <- log2(apply(otu.c, 2, mean)) # add log abundance as properties of vertex/nodes.
vsize 

#Prepare data for plotting
ps_18S_ig <- graph.adjacency(n.c, mode='undirected', add.rownames = TRUE, weighted = TRUE)

Which all seems to work fine but some of the values in my n.c file are negative, is this expected?

Due to this when I run this command I get this error message:
coords.fdr = layout_with_fr(ps_18S_ig)

Error in layout_with_fr(ps_18S_ig) : 
  At core/layout/fruchterman_reingold.c:401 : Weights must be positive for Fruchterman-Reingold layout. Invalid value

Is it an issue I have negative values or do I need to transform the values in some way to remove them?

Many thanks in advance for any suggestions!
Paddy

**Comment by zdk123** [comment]
This is out of scope for the package, but perhaps try scaling between [0, Inf)?
