### ISSUE TITLE
Unable to install SpiecEasi (Pulsar is removed from CRAN)

### ISSUE THREAD

**Issue by kawanoii** [zdk123/SpiecEasi#227]
Hi，
I cant install SpiecEasi, it seem like the Pulsar package is missing and cannot install from CRAN repository.

According to https://cran.r-project.org/web/packages/pulsar/index.html
Package ‘pulsar’ was removed from the CRAN repository.
Formerly available versions can be obtained from the [archive](https://cran.r-project.org/src/contrib/Archive/pulsar).
Archived on 2022-11-25 as issues were not corrected in time.

I have tried to manually extract all Pulsar file to R library, but it still missing some ENV. I think that is because I was not install Pulsar from install.packages()

> devtools::install_github('zdk123/SpiecEasi')
Downloading GitHub repo zdk123/SpiecEasi@HEAD
Skipping 1 packages not available: pulsar
✔  checking for file 'C:\temp\RtmpkjGpkf\remotes1a802b7b7f49\zdk123-SpiecEasi-41448ad/DESCRIPTION'
─  preparing 'SpiecEasi':
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory 'SpiecEasi/inst'
─  looking to see if a 'data/datalist' file should be added
─  building 'SpiecEasi_1.1.2.tar.gz'

* installing *source* package 'SpiecEasi' ...
** using staged installation
** libs
g++  -std=gnu++11 -I"D:/R-4.2.1/include" -DNDEBUG  -I'D:/R-4.2.1/library/Rcpp/include' -I'D:/R-4.2.1/library/RcppArmadillo/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c ADMM.cpp -o ADMM.o
g++  -std=gnu++11 -I"D:/R-4.2.1/include" -DNDEBUG  -I'D:/R-4.2.1/library/Rcpp/include' -I'D:/R-4.2.1/library/RcppArmadillo/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c RcppExports.cpp -o RcppExports.o
g++  -std=gnu++11 -I"D:/R-4.2.1/include" -DNDEBUG  -I'D:/R-4.2.1/library/Rcpp/include' -I'D:/R-4.2.1/library/RcppArmadillo/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c matops.cpp -o matops.o
g++  -std=gnu++11 -I"D:/R-4.2.1/include" -DNDEBUG  -I'D:/R-4.2.1/library/Rcpp/include' -I'D:/R-4.2.1/library/RcppArmadillo/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c sqrtNewton.cpp -o sqrtNewton.o
g++  -std=gnu++11 -I"D:/R-4.2.1/include" -DNDEBUG  -I'D:/R-4.2.1/library/Rcpp/include' -I'D:/R-4.2.1/library/RcppArmadillo/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c svthresh.cpp -o svthresh.o
g++ -shared -s -static-libgcc -o SpiecEasi.dll tmp.def ADMM.o RcppExports.o matops.o sqrtNewton.o svthresh.o -LD:/R-4.2.1/bin/x64 -lRlapack -LD:/R-4.2.1/bin/x64 -lRblas -lgfortran -lm -lquadmath -LC:/rtools42/x86_64-w64-mingw32.static.posix/lib/x64 -LC:/rtools42/x86_64-w64-mingw32.static.posix/lib -LD:/R-4.2.1/bin/x64 -lR
installing to D:/R-4.2.1/library/00LOCK-SpiecEasi/00new/SpiecEasi/libs/x64
** R
** data
** byte-compile and prepare package for lazy loading
Warning in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :
  package 'pulsar' has no 'package.rds' in Meta/
Warning: S3 methods 'getEnvir.default', 'plot.pulsar', 'print.batch.pulsar', 'print.pulsar', 'print.pulsar.refit', 'refit.pulsar', 'update.pulsar' were declared in NAMESPACE but not found
Error in namespaceExport(ns, exports) :
  undefined exports: opt.index<-, batch.pulsar, estrada.class, findConfFile, findTemplateFile, gcvec, get.opt.index, getEnvir, getLamPath, getMaxCov, graph.diss, natural.connectivity, opt.index, pulsar, refit
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace -> namespaceExport
Execution halted
ERROR: lazy loading failed for package 'SpiecEasi'
* removing 'D:/R-4.2.1/library/SpiecEasi'
Warning message:
In i.p(...) :
  installation of package 'C:/temp/RtmpkjGpkf/file1a809895261/SpiecEasi_1.1.2.tar.gz' had non-zero exit status
>

Thanks，

**Comment by kawanoii** [comment]
Never mind, I have solved it by using the archived package to install Pulsar. Shame! I thought it was just extracting all files to the lib dir. XD

**Comment by zdk123** [comment]
Thanks. Apologies I could not fix pulsar on time, newly failing tests are due to a change in an underlying dependency but nothing has changed in the package. Pulsar is also on GitHub: github.com/zdk123/pulsar
