### ISSUE TITLE
Set a license

### ISSUE THREAD

**Issue by laurentheirendt** [zdk123/SpiecEasi#228]
Is it possible to set a license to this repository? I'd like to use it, but I cannot (legally), as it doesn't have a license. Thanks 👍🏼

cc: @zdk123 @genomewalker

**Comment by zdk123** [comment]
The license is GPL (>= 2), as specified in the [DESCRIPTION](https://github.com/zdk123/SpiecEasi/blob/master/DESCRIPTION#L33) file. 

I'd be happy to include a license file if you require it though.

**Comment by laurentheirendt** [comment]
Thanks for your fast response! Yes that would be really helpful 😄 (automated software might not pick up the license otherwise).

**Comment by zdk123** [comment]
done

**Comment by laurentheirendt** [comment]
Thank you so much! 🚀
