### ISSUE TITLE
Error with SpiecEasi implementation of sparCC

### ISSUE THREAD

**Issue by balaphd** [zdk123/SpiecEasi#23]
Hi,

I am getting a below error from SpiecEasi:

> sparcc.out <- sparcc(phyloseqobj.f)
**Error in apply(data, 1, norm_diric) : dim(X) must have a positive length**
> phyloseqobj.f
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 291 taxa and 20 samples ]
tax_table()   Taxonomy Table:    [ 291 taxa by 7 taxonomic ranks ]

Does SpiecEasi does not support phyloseq objects? Could you please help me to solve this issue?

Bala

**Comment by zdk123** [comment]
There is currently no `sparcc` wrapper function for phyloseq objects, but you can extract the data yourself: `sparcc.out <- sparcc(t(as.matrix(otu_table(phyloseqobj.f))))` should work.

**Comment by balaphd** [comment]
Hi,

The solution solved the error and thanks a lot! One more problem arise when
I used the below code:

sparcc.out <-
sparcc(t(as.matrix(otu_table(phyloseqobj.f))),iter=100,inner_iter = 10)
sparcc.graph <- abs(sparcc.out$Cor) >= 0.5
diag(sparcc.graph) <- 0
sparcc.graph <- Matrix(sparcc.graph,sparse=TRUE)
ig.sparcc <- adj2igraph(sparcc.graph)
write_graph(ig.sparcc,file="pre.renov.20.network.sparCC.graphml","graphml")

The original name of the greengenes OTUs were modified as n1,n2,n3...nx and
I don't have any clue which part of your code does this in the sparcc()
function. Could you please check the above code and let me know how to
retain the original OTU name for the nodes.

Best Regards,
Bala
