### ISSUE TITLE
Issue deploying Shiny apps with SpiecEasi?

### ISSUE THREAD

**Issue by Johnson-Stephen** [zdk123/SpiecEasi#24]
Hi,

I've been trying to deploy a Shiny app I've been working on that uses the SpiecEasi package via shinyapps.io. The app works fine locally, but I get the following error whenever I try to deploy: 

[2017-10-25T18:14:20.791341632+0000] Building R package: SpiecEasi (0.1.2)
/mnt/packages/build /mnt
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
* installing to library ‘/usr/local/lib/R/site-library’
* installing *source* package ‘SpiecEasi’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘phyloseq’
ERROR: lazy loading failed for package ‘SpiecEasi’
* removing ‘/usr/local/lib/R/site-library/SpiecEasi’
GET /v1/tasks/?filter=account_id:103158&filter=parent_id:493145227&count=100&offset=0 218ms
################################# End Task Log ################################# 
----- Deployment error -----
Error: Unhandled Exception: Child Task 493145227 failed: Error building image: Error building SpiecEasi (0.1.2). Build exited with non-zero status: 1
 

I made a post on the shinyapps.io Google group to see if it was a problem on their end (https://groups.google.com/forum/#!topic/shinyapps-users/Grr4rkA8-QA) and they seem to think that this is the result of a problem with the DESCRIPTION file causing SpiecEasi to be installed before phyloseq. Is it possible to have the DESCRIPTION file modified?

**Comment by zdk123** [comment]
thanks for the comment. F/u on the google group.

**Comment by zdk123** [comment]
@Johnson-Stephen I just pushed a dev branch to this repo. Can you try to re-deploy your shiny app with that?

**Comment by zdk123** [comment]
@Johnson-Stephen any progress?

**Comment by Johnson-Stephen** [comment]
Sorry for the delayed response -- I just tried running my little test script using this package and get this error:

Loading required package: foo
Error in spiec.easi.phyloseq(phylo_select, method = "mb", lambda.min.ratio = 0.01,  : 
  'Phyloseq' package is not installed
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘foo’

**Comment by zdk123** [comment]
Darn. I'm guessing `foo` is your test package?

What happens if you explicitly load phyloseq before calling `spiec.easi.phyloseq`? 

I'm thinking that I will need to call `require(phyloseq)` from within this function to handle the case where the package is not attached to the namespace but otherwise installed. I don't normally come across this case in an interactive R session.

**Comment by Johnson-Stephen** [comment]
It looks like there is a check for the package `foo` in `dev`: https://github.com/zdk123/SpiecEasi/compare/dev#diff-96dfd1c213ffef6ee2395d5c0b60f792R13

**Comment by zdk123** [comment]
Yeah I just saw that. I am a dolt. Pushing a fix in 5..

**Comment by zdk123** [comment]
Pushed. Also fixed a similar erroneous import of the `boot` package and consolidated the `spiec.easi` docs into one place.

Please try again, thanks.

**Comment by zdk123** [comment]
Coming across this devtools related error now:
https://github.com/hadley/devtools/issues/1649

 Rolling back remote specifications in the description with commit da39122

**Comment by Johnson-Stephen** [comment]
New error when I try and call spiec.easi() using a phyloseq object:

`Error in otu_table(OTU) : object 'OTU' not found`

I think this is the problem but I may be mistaken: https://github.com/zdk123/SpiecEasi/compare/dev#diff-96dfd1c213ffef6ee2395d5c0b60f792R18

It looks like `OTU` is no longer initialized.

**Comment by zdk123** [comment]
thanks. fixed by 3ed5cb4.

**Comment by zdk123** [comment]
now fixed in master
