### ISSUE TITLE
Wrong return value in cov2prec()

### ISSUE THREAD

**Issue by stefpeschel** [zdk123/SpiecEasi#240]
Hey,
I just wanted to use the `cov2prec` function and noticed that instead of the precision matrix, the tolerance value is returned. When looking into the code I saw that a return command is missing. 
Best,
Steffi

**Comment by zdk123** [comment]
oof. thanks for catching that.

**Comment by stefpeschel** [comment]
Great. Thanks for fixing this! 👍
