### ISSUE TITLE
Do not run multi.spiec.easi with unidentical sample scheme

### ISSUE THREAD

**Issue by TeeratatK** [zdk123/SpiecEasi#257]
I work with phyloseq objects. I have a problem with a number of replicates that are not the same (one has 5 and another has 4) for making cross-domain analysis. How to deal with data like this?

Error in spiec.easi.list(datalist, method = method, sel.criterion = sel.criterion,  : 
  Do not run multi.spiec.easi with unidentical sample scheme

**Comment by TeeratatK** [comment]
I'm sorry, my question might make you confuse. I work with 3 phyloseq objects (5 replicates for each, total of 15 samples) and use for creating cross-domain analysis. But one phyloseq object has only 4. I think it causes an error above for this reason. Can you recommend how to overcome this problem?

**Comment by zdk123** [comment]
Same answer. The number of samples and same names must match between all of
the objects for cross domain measurements. There is no built- in way to
subset the samples for inter- vs intra- domain objects. I could consider
adding that but you'd have to do that yourself given the current
implementation
