### ISSUE TITLE
Trouble in installation of SpiecEasi

### ISSUE THREAD

**Issue by Fungitaxon** [zdk123/SpiecEasi#27]
@zdk123 
I have gone through the publication named "Sparse and Compositionally Robust Inference of Microbial Ecological Networks." Indeed, it is really great contribution from all authors.
I intend to use SpiecEasi package to carry out network analysis,however I have encountered installation failure in my R version 3.3.3. Following are the codes that were used to install.
library(devtools)
install_github("zdk123/SpiecEasi", force=TRUE)
library(SpiecEasi)
"C:/PROGRA~1/R/R-33~1.3/bin/x64/R" --no-site-file --no-environ --no-save \
--no-restore --quiet CMD INSTALL \
"C:/Users/Btc/AppData/Local/Temp/RtmpAL5rQO/devtools100c1a2344c8/zdk123-SpiecEasi-d705428" \
--library="C:/Users/Btc/Documents/R/win-library/3.3" --install-tests 
Furthermore, I also downloaded the package in my system local folder and and tried to install, but did not work. By the way huge and Mass packages are already installed in R. 
install.packages("~/Downloads/SpiecEasi.tar.gz", repos = NULL, type="source")
Above mentioned codes also did not work.
I would highly appreciate the solution.
Best,
Abdul

**Comment by zdk123** [comment]
Hi @Fungitaxon. Are you running windows?

Please post the full output after running `install_github("zdk123/SpiecEasi", force=TRUE)`. Just in case, remove existing installations via `remove.packages('SpiecEasi')` first.

**Comment by Fungitaxon** [comment]
Hi@Zdk123. Yes I use windows7 Professional. 
I also tried remove.packages('SpiecEasi')
Removing package from ‘C:/Users/Btc/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Error in find.package(pkgs, lib) : there is no package called ‘SpiecEasi’
Below is the out put, after running, install_github("zdk123/SpiecEasi", force=TRUE). 
Downloading GitHub repo zdk123/SpiecEasi@master
from URL https://api.github.com/repos/zdk123/SpiecEasi/zipball/master
Installing SpiecEasi
"C:/PROGRA~1/R/R-33~1.3/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/Btc/AppData/Local/Temp/RtmpQ74iTQ/devtools1be423986fba/zdk123-SpiecEasi-d705428"  \
  --library="C:/Users/Btc/Documents/R/win-library/3.3" --install-tests 
* installing *source* package 'SpiecEasi' ...
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'phyloseq'
ERROR: lazy loading failed for package 'SpiecEasi'
* removing 'C:/Users/Btc/Documents/R/win-library/3.3/SpiecEasi'
Installation failed: Command failed (1)
It did not work.

**Comment by zdk123** [comment]
Thanks... This is a known issue that I will push a fix for soon. 

If you want to use the phyloseq package to handle your data in R, see [this link](https://bioconductor.org/packages/release/bioc/html/phyloseq.html) and re-run the SpiecEasi installation as-is.

Otherwise, you can install SpiecEasi from the dev branch using:
`install_github('zdk123/SpiecEasi', ref='dev')`

thanks

**Comment by Fungitaxon** [comment]
You are welcome. Following installation command worked.
install_github('zdk123/SpiecEasi', ref='dev')
I did not encounter any problem in installation.
How ever I have some questions, apart from installation
1- Is it possible to carry out correlation between relative abundance of OTUs, while knowing that there is variation in number of sites and OTUs. They do not have equal dimension. I am also aware that some publication recommend the use of Spearman's correlation in microbiome studies.
Could you please share with me your official email ID, as I have questions regarding the use of SpiesEasi and Sparcc?

**Comment by zdk123** [comment]
zdkurtz@gmail.com

**Comment by zdk123** [comment]
now fixed in master
