### ISSUE TITLE
How to build Rdata from OTU table

### ISSUE THREAD

**Issue by XuefengGao** [zdk123/SpiecEasi#28]
Hello Dr. Kurtz,

I am currently using SpiecEasi for my own project. I have successfully ran your tutorial. However,
I also tried the tutorial from another resource "http://psbweb05.psb.ugent.be/conet/microbialnetworks/spieceasi.php"

 I think it is more easy to work on RData instead of biom file. However, I have no idea how to make my own RData from such 16S OTU table? Can you provide some information please?

Best regards,
Ryan

**Comment by zdk123** [comment]
[see the help page](https://stat.ethz.ch/R-manual/R-devel/library/base/html/save.html) for R's `save` function.
