### ISSUE TITLE
How to get edge weights for plotting network in igraph?

### ISSUE THREAD

**Issue by andrewd001** [zdk123/SpiecEasi#3]
Hello,

When plotting a network in igraph, one can provide attributes such as edge weights that are used to (for example) indicate the magnitude or direction of edges between nodes. 

I'm curious to know whether this can be done from the outputs of the spiec-easi pipeline. If I have a spiec-easi object named "se" then I know that se$refit is the optimal graph path, but it consists only of ones and zeros. Is magnitude data provided anywhere? For example, is it contained in se$beta, or is that something else?

Thanks,

Andrew.

**Comment by zdk123** [comment]
Yes.. for MB method, edge weights are included in se$beta (model coefficient from neighborhood selection, at each lambda parameter).

**Comment by andrewd001** [comment]
Excellent, many thanks for the confirming that, much appreciated. 

Andrew.
