### ISSUE TITLE
Error message Phyloseq

### ISSUE THREAD

**Issue by a2vo** [zdk123/SpiecEasi#32]
Hi,

I have tried to run spiec.easi function but I get an error message regarding Phyloseq while have loaded Phyloseq and it is running properly:
> spiec.out = spiec.easi(S16.f, method="mb",icov.select.params=list(rep.num=20))
Loading required package: foo
Error in spiec.easi.phyloseq(S16.f, method = "mb", icov.select.params = list(rep.num = 20)) : 
  'Phyloseq' package is not installed
De plus : Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘foo’

I have seen that someone came across the problem and that it should be fixed but... Can you help me with that ?

Thanks

**Comment by zdk123** [comment]
Please install the dev branch of this repo, which contains the fix. This
will be pulled into master soon. Thanks.

**Comment by davis164** [comment]
I also got this error. How do I install the dev branch into R? I tried install_github("zdk123/SpiecEasi", ref = "develop") but it gave me an error: Downloading GitHub repo zdk123/SpiecEasi@develop
from URL https://api.github.com/repos/zdk123/SpiecEasi/zipball/develop
Installation failed: 404: Not Found
 (404)

Thanks!

**Comment by davis164** [comment]
Oh! Figured it out. "dev" not "develop".

**Comment by zdk123** [comment]
thanks. Closing issue.

**Comment by zdk123** [comment]
now fixed in master
