### ISSUE TITLE
Is there a function to understand keystone OTUs?

### ISSUE THREAD

**Issue by AndreaQ7** [zdk123/SpiecEasi#34]
Hello everyone,

I was reading and interesting work that used SpiecEasi and detect the possible keystone OTU for each newtork, identifying the top taxa that have hgher node degree and hig betweenness centrality ( as thay wrote " Betweenness centrality vs. Degree. For each node, we computed the degree and betweenness centrality. The top two OTUs by betweenness are consistent with degree, and are highlighted in gray.").
I found this is very interesting but i did not understand if there is a specific function to compute it within this package? thanks a lot for you support
p.s. I attach the link to the work (https://genomemedicine.biomedcentral.com/articles/10.1186/s13073-016-0297-9)

**Comment by zdk123** [comment]
The are functions to calculate these metrics are in the igraph package.
