### ISSUE TITLE
there is no package called ‘foo’

### ISSUE THREAD

**Issue by hshcao** [zdk123/SpiecEasi#36]
I run the tutorial with this function:
spiec.easi(phyloseqobj.f, method="mb",icov.select.params=list(rep.num=20))
and run into error 
nd found the error with this:

> # run SPIEC-EASI, other method being glasso
> spiec.out=spiec.easi(phyloseqobj.f, method="mb",icov.select.params=list(rep.num=20))
**Loading required package: foo
Error in spiec.easi.phyloseq(phyloseqobj.f, method = "mb", icov.select.params = list(rep.num = 20)) : 
  'Phyloseq' package is not installed
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘foo’**

This problem was encountered many times following the tutorial here at Github or the R cran PDF or the Microbial association network construction tutorial.

Is that a spieceasi problem or an R base problem?

Thanks

HC

**Comment by zdk123** [comment]
No it's a simple typo in the master branch... please install from the dev
branch. install_github ('zdk123/SpiecEasi', ref='dev')

Thanks.

**Comment by hshcao** [comment]
Thanks for your response.
I did this:
library(devtools)
#install_github("zdk123/SpiecEasi")
branch.install_github ('zdk123/SpiecEasi', ref='dev')

but got this error message:
> library(devtools)
> branch.install_github ('zdk123/SpiecEasi', ref='dev')
Error in branch.install_github("zdk123/SpiecEasi", ref = "dev") : 
  could not find function "branch.install_github"

**Comment by hshcao** [comment]
I got it. I will let you know if it works.
install_github ('zdk123/SpiecEasi', ref='dev')

**Comment by hshcao** [comment]
Thanks you. it worked

**Comment by zdk123** [comment]
now fixed in master
