### ISSUE TITLE
The problem about the data format

### ISSUE THREAD

**Issue by joshualiuxu** [zdk123/SpiecEasi#39]
Hello,I have a question about the data format. 
Generally, the package requests the data is json biom type,however,whether have a way to transform the txt OTU table into the biom?or directly revise the phyloseq based on the OTU txt?
Thanks a lot

**Comment by adnbps** [comment]
You can use SpiecEasi with a tab-delimited counts matrix (this is in the tutorial)

**Comment by joshualiuxu** [comment]
@adnbps thank u so much 
I found a way via Phyloseq package 
use code import_qiime can deal with txt document import
