### ISSUE TITLE
Can you get a covariance matrix as the SparCC method

### ISSUE THREAD

**Issue by ZeweiSong** [zdk123/SpiecEasi#4]
Is it possible to output the covariance matrix for Speci.easi? I was wondering how you can tell the type of interactions (negative and positive).

**Comment by zdk123** [comment]
Yes, this is possible using glasso routine (method="glasso"). Then the optimal covariance matrix is stored in obj$opt.cov. Alternatively, if you like Neighbor selection (mb) and just need the signs, you can inspect the coefficient matrix (obj$beta[[obj$opt.ind]], but fair warning, this matrix won't be symmetric, but usually the signs agree).

**Comment by ZeweiSong** [comment]
Thanks, Zack, and also thanks for you reply of my email.

Does value of me covariance correspond to the strength of correlation of two OTUs? Or does it has different meaning and we can only inference a relationship but not its strenght?

Zewei

**Comment by zdk123** [comment]
Yes, and I'd recommend transforming the covariance to a correlation matrix (cov2cor) to standardize the entries.

Be aware, however, that the entries in the covariance/correlation matrix are based on a penalized estimator so don't expect to see to see entries as large as you'd observe from the empirical correlation.

**Comment by ZeweiSong** [comment]
Thanks, one last question.
Does the OTUs kept their original order in the output?

Zewei

**Comment by zdk123** [comment]
yes
