### ISSUE TITLE
How to extract the correlation matrix (p x p) from the results

### ISSUE THREAD

**Issue by RootQJZ** [zdk123/SpiecEasi#43]
Hello,

Thanks for the great program! I am wondering how to extract the correlation matrix (p x p, p is the number of OTUs) from the 'mb' model results or(and) 'glasso' model results after running the spiec.easi() in r, which can be used for the other downstream analysis?

Any ideas? Thanks!

**Comment by zdk123** [comment]
This is detailed in the README of this repo. Please see the code related to the histograms in: https://github.com/zdk123/SpiecEasi#analysis-of-american-gut-data

The MB does not result in a covariance matrix. The glasso method does, which can be converted to correlations via `cov2cor`.
