### ISSUE TITLE
Error of excuting "call <- do.call("update", c(pulsar.params, list(object = list(call = call),evaluate = FALSE)))"

### ISSUE THREAD

**Issue by xiaoyandong08** [zdk123/SpiecEasi#47]
Dear authors,

Thanks for your efforts and sharing your code. However, when I ran your example posted in github, e.g., **se <- spiec.easi(X, method='mb', lambda.min.ratio=1e-2, nlambda=15)**, there exists an error as 
Error in update.list(criterion = "stars", thresh = 0.05, object = list( : 
  argument "new" is missing, with no default

I found that it occurs at call <- do.call("update", c(pulsar.params, list(object = list(call = call),evaluate = FALSE))).

DO you know how to deal with this?
Thanks for your help!

**Comment by xiaoyandong08** [comment]
After I reinstalled, the error still exists. The error occurred at gdata package.
update(object,
       new,
       unnamed=FALSE,
       ...)
Parameter new is missing.
My platform is Mac High Sierra 10.13.5, R version 3.5.1.

**Comment by zdk123** [comment]
This is odd... gdata is not in SpiecEasi's dependency graph, so I wonder what the conflict is. Can you try unloading gdata?

**Comment by zdk123** [comment]
Confirmed that I can reproduce this error when the gdata package is loaded prior to SpiecEasi.

**Comment by zdk123** [comment]
Hi @xiaoyandong08, I just created a patch. Can you try again with:
`devtools::install_github("zdk123/SpiecEasi", ref='patchupdate')` please?

**Comment by xiaoyandong08** [comment]
Yes. It's OK. Thanks for your help!

**Comment by MarinaC9** [comment]
Hello

I have the same error than @xiaoyandong08 

When I try devtools::install_github("zdk123/SpiecEasi", ref='patchupdate'), I get :
Downloading GitHub repo zdk123/SpiecEasi@patchupdate
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
 unable to open the URL 'https://api.github.com/repos/zdk123/SpiecEasi/tarball/patchupdate'

Do you know what can I do ?

Thanks a lot

**Comment by zdk123** [comment]
This branch doesn't exist anymore, just install from `master` branch (the default ref).

**Comment by acarrell** [comment]
Hello. I am encountering the same error but with the newest version. I have installed following the instructions in the README file. Running macOS 10.14.6 and R 4.0.2. Any advice?

> se.mb.16S <- spiec.easi(physeq16S, method='mb', lambda.min.ratio=1e-2, nlambda=20, pulsar.params=list(rep.num=50))
Applying data transformations...

Error in update.list(rep.num = 50, criterion = "stars", thresh = 0.05,  : 
  argument "new" is missing, with no default

**Comment by zdk123** [comment]
Can you check the package version for pulsar?

**Comment by acarrell** [comment]
pulsar 0.3.7

**Comment by zdk123** [comment]
I found a regression in the code that set back this error. Can you help by reinstalling from the patch branch and try again?
```sh
devtools::install_github('zdk123/SpiecEasi', ref='patch')
```

**Comment by acarrell** [comment]
That solved it! Thank you for your rapid response.
