### ISSUE TITLE
How to interpret optimal sparsity of zero?

### ISSUE THREAD

**Issue by andrewd001** [zdk123/SpiecEasi#5]
I've been applying spiec-easi to a variety of amplicon datasets, and sometimes it determines that the optimal sparsity is zero, so that the resulting network contains no edges. I'm curious about why this might happen. The datasets in question contain several hundred OTUs in about 30 samples. 

This is the code I used:
> se.mb <- spiec.easi(OTUtable.t, method='mb', lambda.min.ratio=1e-2, nlambda=25, icov.select.params=list(rep.num=50))

In one case, these are sparsity values that resulted:
> se.mb$sparsity 
0.000000000 0.001467393 0.002061033 0.002597668 0.003086144 0.003608036 0.004139757 0.004724552 0.005305415 0.005977683 0.006683369 0.007415591 0.008209732 
0.009079553 0.009947408 0.010809366 0.011721449 0.012762285 0.013840470 0.014893101 0.016008633 0.017153652 0.018338967 0.019473174 0.020587724

But optimal sparsity is zero:
> se.mb$opt.sparsity
0.000000000

Taken literally, I presume this would mean there are no significant co-occurrences, which is unexpected. Is it possible that the optimal sparsity identification method has failed in some way?

**Comment by zdk123** [comment]
It's possible that there are no significant associations, but it is more likely that you need to lower lambda.min.ratio. Try something like 5e-2 or 1e-3. Fair warning: this can significantly slow down the computation, especially if not running stability selection in parallel.

**Comment by andrewd001** [comment]
Aha. Lowering the lambda.min.ratio to 1e-3 indeed gave a more expected outcome. Thanks for the suggestion.
