### ISSUE TITLE
Phyloseq object problem

### ISSUE THREAD

**Issue by davidvilanova** [zdk123/SpiecEasi#50]
Hi,
I get the following error....
Any idea ?
```
> physeq
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 36 taxa and 273 samples ]
sample_data() Sample Data:       [ 273 samples by 19 sample variables ]
tax_table()   Taxonomy Table:    [ 36 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 36 tips and 35 internal nodes ]


mb <- spiec.easi(physeq, method='mb', lambda.min.ratio=1e-2,nlambda=20, icov.select.params=list(rep.num=20,ncores=3))
Applying data transformations...
Selecting model with pulsar using stars...
Fitting final estimate with mb...
done
> ig <- adj2igraph(mb$refit,  rmEmptyNodes=T, vertex.attr=list(name=taxa_names(physeq)))  #Only show connected nodes
Error in mde(x) : (list) object cannot be coerced to type 'double'

```
I´m running 
` SpiecEasi            * 1.0.1     2018-08-10 Github (zdk123/SpiecEasi@8bda6ed) 
`

**Comment by zdk123** [comment]
This isn't a phyloseq problem, but the SpiecEasi output changed a bit in the recent release.

See:
https://github.com/zdk123/SpiecEasi#working-with-phyloseq

So try:
```
ig <- adj2igraph(getRefit(mb))
```
or equivalently:
```
ig <- adj2igraph(mb$refit$stars)
```
The output `mb$refit` is now a list with one member (named `stars`, the refit of the stars-selected model.

**Comment by davidvilanova** [comment]
Thanks. work !!!
I´m using the following code based on the tutorial published but it´s now broken. I´m coloring edges based on covariance matrix and adding a weight so that i can later plot a nice connection graph. How can i reproduce the code with the new updates ?

This is empty now ??
`otu.ids=colnames(mb$data)
`

```
# Add edged colors based on nodes connected
#The inverse covariance matrix is obtained via a form of regression
betaMat=as.matrix(symBeta(getOptBeta(mb)))

otu.ids=colnames(mb$data)
edges=E(ig)
edge.colors=c()
edge.weight=c()
for(e.index in 1:length(edges)){
  adj.nodes=ends(ig,edges[e.index])
  xindex=which(otu.ids==adj.nodes[1])
  yindex=which(otu.ids==adj.nodes[2])
  beta=betaMat[xindex,yindex]
  if(beta>0){
    edge.colors=append(edge.colors,"forestgreen")
    edge.weight= format(beta*100,digits=3)

  }else if(beta<0){
    edge.colors=append(edge.colors,"red")
    edge.weight= format(beta*100,digits=3)

    
  }
}


E(ig)$color=edge.colors
E(ig)$weight=edge.weight

```

**Comment by davidvilanova** [comment]
Hi @zdk123 
Any news on this ?

**Comment by zdk123** [comment]
@davidvilanova what tutorial are you going off of?

You can always get taxa names from your input dataset.

**Comment by davidvilanova** [comment]
Hi,
The idea is to get negative and positive correlations. Following this tutorial
http://psbweb05.psb.ugent.be/conet/microbialnetworks/solutions.php#spieceasiedge

Not working for me anymore.

**Comment by davidvilanova** [comment]
Finally fixed

**Comment by Gian77** [comment]
Hello @davidvilanova and @zdk123 

I am having the same problem, how can i fix it? See below

`> spiec_prok`
`Pulsar-selected refit of sparseiCov `
`Path length: 20 `
`Graph dim:   115 `
`Criterion:`
  `stars... sparsity 0.0275`

`> betaMat = as.matrix(symBeta(getOptBeta(spiec_prok)))`
``Error in i`f (nrow(beta) != ncol(beta)) { : argument is of length zero``

Thank you!

G.

**Comment by hites77** [comment]
Code I ran: 

pargs2 <- list(rep.num=50, seed=10010, ncores = 9)
net.c <- spiec.easi(ps2, method='mb', lambda.min.ratio=1e-2, nlambda=20, sel.criterion='stars', 
                    pulsar.select=TRUE, pulsar.params=pargs2)
ig <- adj2igraph(net.c$refit$stars)
plot_network(ig, ps2, type='taxa', color="Rank3")

Error i faced:

**Error in `$<-.data.frame`(`*tmp*`, "id", value = 1:0): replacement has 2 rows, data has 0
Traceback:

1. plot_network(ig, ps2, type = "taxa", color = "Rank3")
2. `$<-`(`*tmp*`, "id", value = 1:0)
3. `$<-.data.frame`(`*tmp*`, "id", value = 1:0)
4. stop(sprintf(ngettext(N, "replacement has %d row, data has %d", 
 .     "replacement has %d rows, data has %d"), N, nrows), domain = NA)**


(ps2 is my phyloseq object)
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 1456 taxa and 16 samples ]
sample_data() Sample Data:       [ 16 samples by 3 sample variables ]
tax_table()   Taxonomy Table:    [ 1456 taxa by 7 taxonomic ranks ]
refseq()      DNAStringSet:      [ 1456 reference sequences ]

**Comment by Madegwa** [comment]
Hello, thanks for the awesome package. I just recently started to use it and was going through the tutorial. I ran to this error when i tried to use this command (I used a phyloseq object to run the command)

#obtain the number of edges in the network from the matrix of regression coefficients
  otu.ids=colnames(spiec.out$data)
  edges=E(spiec.graph)
  edge.colors=c()
  for(e.index in 1:length(edges))
    adj.nodes=ends(spiec.graph,edges[e.index])
    xindex=which(otu.ids==adj.nodes[1])
    yindex=which(otu.ids==adj.nodes[2])
    beta=betaMat[xindex,yindex]
    if(beta>0){
      edge.colors=append(edge.colors,"forestgreen")
    }else if(beta<0){
      edge.colors=append(edge.colors,"red")
    }

Error in if (beta > 0) { : argument is of length zero

Any assistance will be highly appreciated

**Comment by zdk123** [comment]
I would need a reproducible example but usually this means beta is a NULL or another data type without length.

**Comment by kcbeng** [comment]
> Finally fixed

Hi davidvilanova ,
How did you fix this? Could you please share your solution here.
Thanks
Beng

**Comment by kcbeng** [comment]
> Hello, thanks for the awesome package. I just recently started to use it and was going through the tutorial. I ran to this error when i tried to use this command (I used a phyloseq object to run the command)
> #obtain the number of edges in the network from the matrix of regression coefficients
> otu.ids=colnames(spiec.out$data)
> edges=E(spiec.graph)
> edge.colors=c()
> for(e.index in 1:length(edges))
> adj.nodes=ends(spiec.graph,edges[e.index])
> xindex=which(otu.ids==adj.nodes[1])
> yindex=which(otu.ids==adj.nodes[2])
> beta=betaMat[xindex,yindex]
> if(beta>0){
> edge.colors=append(edge.colors,"forestgreen")
> }else if(beta<0){
> edge.colors=append(edge.colors,"red")
> }
> Error in if (beta > 0) { : argument is of length zero
> Any assistance will be highly appreciated

Hi,
I have the same problem. Here is a reproducible example
http://psbweb05.psb.ugent.be/conet/microbialnetworks/spieceasi.php

**Comment by zdk123** [comment]
@kcbeng what package version are you using? I believe this was a NULL object being assignment to `betaMat` due to an API change.
