### ISSUE TITLE
SVN requirement

### ISSUE THREAD

**Issue by zdk123** [zdk123/SpiecEasi#51]
An unnecessary SVN requirement has apparently been introduced in the latest version.

This seems to be a bioconductor dependency introduced by the `remote` line in the description file. Issue was reported by STAMPS users and a few times since then and makes package installation unnecessarily more difficult on certain OSes.

**Comment by zdk123** [comment]
patch in dev branch seems to fix the issue, and travis build passes:
https://travis-ci.org/zdk123/SpiecEasi/builds/416086231

**Comment by BinhongLiu** [comment]
Recently I am trying to install SpiecEasi package in RStudio. I follow the instructions but I keep getting a similar error message: Installation failed: SVN does not seem to be installed on your system.
![image](https://user-images.githubusercontent.com/35453307/44295452-a5eb5100-a2db-11e8-98a1-86dc7a71e738.png)

 By the way, my system is windows 10 pro (64x), but not Ubuntu. Do you have any solutions for this problem in RStudio? Thank you very much.

**Comment by zdk123** [comment]
@BinhongLiu Fixed on master, please try again.

**Comment by BinhongLiu** [comment]
Thank you so much. The package can be installed successfully!

**Comment by zdk123** [comment]
fixed in PR #52
