### ISSUE TITLE
Exemple of neg and pos coefficient and plots with phyloseq

### ISSUE THREAD

**Issue by davidvilanova** [zdk123/SpiecEasi#54]
Hi,
I have added a use case with a phyloseq object to color edges based on the coefficient of regression, positive or negative (green or red). I have added the coefficient in the edges.
Since it took some time to put it all together i though it could help others looking for similar plots. 

Feel free to use as an example.

```
####
library(SpiecEasi)
library(phyloseq)
library(ggnet)

# Col vector up to 74 color samples
col_vector74 = c("#7FC97F","#BEAED4","#FDC086","#FFFF99","#386CB0","#F0027F","#BF5B17","#666666","#1B9E77","#D95F02","#7570B3","#E7298A","#66A61E","#E6AB02","#A6761D","#666666","#A6CEE3","#1F78B4","#B2DF8A","#33A02C","#FB9A99","#E31A1C","#FDBF6F","#FF7F00","#CAB2D6","#6A3D9A","#FFFF99","#B15928","#FBB4AE","#B3CDE3","#CCEBC5","#DECBE4","#FED9A6","#FFFFCC","#E5D8BD","#FDDAEC","#F2F2F2","#B3E2CD","#FDCDAC","#CBD5E8","#F4CAE4","#E6F5C9","#FFF2AE","#F1E2CC","#CCCCCC","#E41A1C","#377EB8","#4DAF4A","#984EA3","#FF7F00","#FFFF33","#A65628","#F781BF","#999999","#66C2A5","#FC8D62","#8DA0CB","#E78AC3","#A6D854","#FFD92F","#E5C494","#B3B3B3","#8DD3C7","#FFFFB3","#BEBADA","#FB8072","#80B1D3","#FDB462","#B3DE69","#FCCDE5","#D9D9D9","#BC80BD","#CCEBC5","#FFED6F")


## Load round 2 of American gut project
data('amgut2.filt.phy')
getrank="Rank3" ## Note that depending on your object this could be "Class" or "Genus"...

se.mb.amgut2 <- spiec.easi(amgut2.filt.phy, method='mb', lambda.min.ratio=1e-2,
                           nlambda=20, pulsar.params=list(rep.num=50))
ig2.mb <- adj2igraph(getRefit(se.mb.amgut2),  rmEmptyNodes=T, vertex.attr=list(name=taxa_names(amgut2.filt.phy)))

# Add edged colors based on nodes connected
#The inverse covariance matrix is obtained via a form of regression
betaMat=as.matrix(symBeta(getOptBeta(se.mb.amgut2)))

#otu.ids=colnames(mb$data)
otu.ids <- colnames(se.mb.amgut2[[1]]$data)

edges=E(ig2.mb)
edge.colors=c()
edge.weight=c()
for(e.index in 1:length(edges)){
  adj.nodes=ends(ig2.mb,edges[e.index])
  xindex=which(otu.ids==adj.nodes[1])
  yindex=which(otu.ids==adj.nodes[2])
  beta=betaMat[xindex,yindex]
  if(beta>0){
    edge.colors=append(edge.colors,"forestgreen")
    #edge.weight= format(beta*100,digits=3)
    weight= format(beta*100,digits=3)
    edge.weight=append(edge.weight,weight)
    
    cat("Beta pos:",beta,"\n")
    
  }else if(beta<0){
    edge.colors=append(edge.colors,"red")
    weight= format(beta*100,digits=3)
    edge.weight=append(edge.weight,weight)
    
    cat("Beta neg:",beta,"\n")
    
    
  }
}

E(ig2.mb)$color=edge.colors
E(ig2.mb)$weight=edge.weight

#How many nodes connected at specific rank
nb_nodes <- vcount(ig2.mb)
tax_table(amgut2.filt.phy) <- tax_table(amgut2.filt.phy)[,getrank]
otu_ids <- V(ig2.mb)$name
idx <- which(row.names(tax_table(amgut2.filt.phy)) %in% otu_ids)
taxa <- as.character(tax_table(amgut2.filt.phy)[,getrank])[idx]

ig2 <- asNetwork(ig2.mb)
network.vertex.names(ig2) <- taxa

net <- ig2
net %v% getrank = as.character(taxa)
y= col_vector74[1:nb_nodes]
names(y) <- levels(as.factor(taxa))

#Plot the network

p <-  ggnet2(net,
             color = getrank,
             palette = y,
             alpha = 0.75,
             size = 6, 
             edge.label = "weight", 
             edge.size=1,
             edge.color="color",
             edge.alpha = 0.5,
             label = TRUE, 
             label.size = 4)
```

<img width="2294" alt="screen shot 2018-08-30 at 15 02 40" src="https://user-images.githubusercontent.com/11404840/44853527-7dae0b80-ac66-11e8-951a-80a6e22bf1ed.png">

**Comment by zdk123** [comment]
Thanks for the contribution, but I feel like your loop is inefficient. I.e. See Circle 3 in the [R inferno](https://www.burns-stat.com/pages/Tutor/R_inferno.pdf)

Consider instead the vectorized construction:
```
optbeta <- as.matrix(symBeta(getOptBeta(se.mb.amgut2)))
edge_cols <-  ifelse(optbeta>0, 'forestgreen', 'red')[upper.tri(optbeta) & optbeta!=0]
ig2.mb <- adj2igraph(getRefit(se.mb.amgut2),  rmEmptyNodes=TRUE,
                                    vertex.attr=list(name=taxa_names(amgut2.filt.phy)),
                                    edge.attr=list(color= edge_cols))
```

**Comment by davidvilanova** [comment]
Sure. There’s always space for optimization. Always a balance between getting things done and spend more time doing code optimization. Note that in the loop i also capture weights. Haven't fixed yet to modify the edge.size with the 

There is still one question i have, how do you know what is the strenght of the coefficients that you obtain? Meaning how strong the relationship between two nodes is?
Thanks for the comments.

**Comment by zdk123** [comment]
This is given by  the absolute value of the coefficients (the beta matrix). However, due to the penalization/shrinkage, it is not really possible to compare association strengths across experiments but this is generally true of any LASSO type regression.

**Comment by davidvilanova** [comment]
Ok makes sense, for just one experiment is the size of the coefficient an indicator of the effect size.  So can you rank by coefficient?

**Comment by zdk123** [comment]
I've certainly abused LASSO coefficients in this way, but  _technically_ this is not correct either.
LASSO coefficients are not necessarily rank-consistent w.r.t. the lambda path. So, doing something like [least-squares refitting](https://arxiv.org/pdf/1306.0113.pdf) may not even reduce prediction bias, let alone give you an useful effect size.

@muellsen will may specific recommendations.

**Comment by ZarulSaurus** [comment]
Hello Dr Kurtz,

Can I ask, if I am interested to use mode lasso, while coloring the edges by coefficients. However, methods like getOptBeta and symBeta are reserved for object created from mb method. So, how can I color those edges? Is this correct?

`
se.mb.amgut2 <- spiec.easi(amgut2.filt.phy, method='glasso', pulsar.params = list(ncores = 4, rep.num=50))

opt1 <- as.matrix(cov2cor(getOptCov(se.mb.amgut2)))

edge_cols <-  ifelse(opt1>0, 'forestgreen', 'red')[upper.tri(opt1) & opt1!=0]

ig2.mb <- adj2igraph(getRefit(se.mb.amgut2),  rmEmptyNodes=TRUE,
                                    vertex.attr=list(name=taxa_names(amgut2.filt.phy)),
                                    edge.attr=list(color= edge_cols))
`

**Comment by zdk123** [comment]
sorry I had a reply to this, but I must've forgot to leave the comment. For `glasso` mode, use `getOptCov` and take the signs of the covariances.

**Comment by mgosborn** [comment]
Hello! I am also trying to color edges using the solution @zdk123 suggested, but am finding that when I try to plot the edges are overwritten to match the color of the nodes. It seems that I have the incorrect plot command. Could you recommend an alternative? My script is below: 

optbeta <- as.matrix(symBeta(getOptBeta(se.mb.mydata)))
edge_cols <-  ifelse(optbeta>0, 'forestgreen', 'red')[upper.tri(optbeta) & optbeta!=0]
ig2.mb <- adj2igraph(getRefit(mydata),  rmEmptyNodes=TRUE,
                                    vertex.attr=list(name=taxa_names(mydata.phy)),
                                    edge.attr=list(color= edge_cols))
plot_network(ig2.mb, mydata.phy, type='taxa', color = "Phylum", label = NA)

Thank you!

**Comment by xkcococo** [comment]
@davidvilanova

Thanks for providing this example!
I am trying to use it but I have an error message : Error in E(ig2.mb) : could not find function "E"

Is there any source or function that needs to be loaded?

Thanks in advance!

**Comment by zdk123** [comment]
The plot_network function may have changed - I'll look into that. @xkcococo you need to load the igraph package.

**Comment by xkcococo** [comment]
@zdk123 
Thanks! After installed igraph, I found this function E().
But another error comes, Error in asNetwork(ig2.mb) : could not find function "asNetwork".

Is there any new version of this code that could be used as a template or example about plotting neg and pos coefficient with phyloseq?

Thanks!
