### ISSUE TITLE
A error in multidomain spiec-easi function

### ISSUE THREAD

**Issue by wanglu2014** [zdk123/SpiecEasi#55]
[error.zip](https://github.com/zdk123/SpiecEasi/files/2345946/error.zip)

Thank for your attention.
A code has been posted at here.
I am sure that input data is a list of numeric matrice, however, the error appears.

OTU.UF = otu_table(com_wl,taxa_are_rows=F)
phyloseqobj1 = phyloseq(OTU.UF)#, tax.UF)
OTU.UF2 = otu_table(com_wlf,taxa_are_rows=F)
phyloseqobj2 = phyloseq(OTU.UF2)#, tax.UF)
se.hmp2 <- spiec.easi(list(phyloseqobj1,phyloseqobj2), method='mb', lambda.min.ratio=1e-2, nlambda=20, icov.select.params=list(rep.num=20))
se.hmp2 <- spiec.easi(list(com_wl,com_wlf), method='mb', lambda.min.ratio=1e-2, nlambda=20, icov.select.params=list(rep.num=20))

![default](https://user-images.githubusercontent.com/12541282/44992952-6acf6a00-afcb-11e8-9865-bdd451653e1e.png)
The rdata file has attached.
Thank for your time.

**Comment by zdk123** [comment]
Looks like you are using an old version of SpiecEasi. 
What is the output of `packageVersion('SpiecEasi')`?

I don't get any errors on my machine, so try upgrading using devtools please.

**Comment by wanglu2014** [comment]
Thank for your suggestion. It worked. You always timely reply with kindness.
