### ISSUE TITLE
Error in mde(x) : (list) object cannot be coerced to type 'double'

### ISSUE THREAD

**Issue by yuqing-feng** [zdk123/SpiecEasi#56]
Hi,
I am running the examples from SpiecEasi-R package tutorial (Aug 9, 2016). When I ran the code--'ig.ctl <- adj2igraph(se.amgut.ctl$refit, vertex.attr=list(name=taxa_names(amgut.ctl)))', it threw out the error: 'Error in mde(x) : (list) object cannot be coerced to type 'double''.
Detail information:
    Rstudio version: 3.5.1
    packageVersion('SpiecEasi'): 1.0.2
    packageVersion('igraph'): 1.2.2
    macOS

**Comment by zdk123** [comment]
That tutorial is out of date as of SpiecEasi version 1.0.0 and higher. 

Please consult this repo's Readme and the help page for the new getter functions: ?getRefit

**Comment by yuqing-feng** [comment]
Thank you for your help
