### ISSUE TITLE
Lambda Parameters and a few other questions

### ISSUE THREAD

**Issue by ZarulSaurus** [zdk123/SpiecEasi#57]
Hello Dr Kurtz,

A few questions, I notice that in the tutorials, you use _lambda.min.ratio_ and _nlambda_ parameters. I tried to open the help page for spiec.easi (_?spiec.easi_), but these two parameters were not there. How do I learn more of these parameters? Also, are there any other parameters that might not be in the help page?

I am not from a strong statistics background, so I'm sorry to have to ask this. To choose the ideal lambda value, I am assuming that the best nlambda value is one maximise true positive while trying to reduce false positive. And, spiec.easi automatically finds this value, which is stored into $getreFit value. Am I right?

**Comment by zdk123** [comment]
1. Take a look at the help page for `huge` function in the huge package. All undocumented arguments are passed down to this function, but I agree this fact should be documented better in `spiec.easi`.

2. This is not quite right. the [StARS procedure](https://arxiv.org/pdf/1006.3316.pdf) models the sparsistency of the network models. The benefit to this procedure is that we transform some data dependent parameter (lambda) into an interpretable quantity (the stars variability). This guides us towards the stable model, where most true positive edges are likely to be included.

In SPIEC-EASI, the StARS procedure is run first to determine the optimal lambda, then the model is refit with all the samples. You can access adjacency matrix of the associated network using `getRefit(out)`
