### ISSUE TITLE
plotting negative and postive associations in igraph

### ISSUE THREAD

**Issue by nyoungb2** [zdk123/SpiecEasi#6]
I'd don't think the example in your README explains how to plot negative and positive associations (as in Fig 6 of the SPIEC-EASI paper) with igraph. What's the best way of doing that with igraph?
Thanks!

**Comment by zdk123** [comment]
Hi @nyoungb2: I'm going to close this issue, since this isn't a SpiecEasi bug, per se. Please see the documentation for the igraph package for help with plotting networks.
