### ISSUE TITLE
About P-value 

### ISSUE THREAD

**Issue by joshualiuxu** [zdk123/SpiecEasi#63]
Hi, thanks for a very nice method to analyze microbial network And I have a problem about how we know  the consequence network is reliable? Can we get a result similiarly p-value?  and  in  when I calculate the unweight/weighted edge value as   **SpiecEasi - R package tutorial**,  I  also don't know  how to get the p-value or ρ just like these.
Thank you

**Comment by zdk123** [comment]
Sorry for the extreme delay, somehow I didn't see this issue... 
We don't have p-values per se, but a good proxy is the edge stability which you can extract from spiec.easi output using the function `getOptMerge`. This will give you an adjacency matrix with a number between 0-1, corresponding to the fraction of networks, constructed with 80% subsamples, that also contained that edge. This isn't exactly an empirical p-value (like SparCC gives you) since we use sampling without replacement rather than the bootstrap, but the principal is similar.

**Comment by joshualiuxu** [comment]
I'm so touched what's going on。hhhh   Thank you so much!! I will try to extract the edge stability from spieceasi output. The reason I want to do this is for the network module, I want to divide some parts to find the hubs in this module and further explore ecological meaning.  Hope keeping contact.  Thank U!!!  ╰(*°▽°*)╯

**Comment by joshualiuxu** [comment]
halo! Rencently  I find I have another question that the information about edge stability extracting  from spieceasi output via  function getOptMerge. Due to the link produced by inverse covariance, what's way to produce the 0-1 edge stability? Thank U!!

**Comment by joshualiuxu** [comment]
OOO I re-describe my question. I understand the network algorithm between OTU and OTU based on inverse covariance, but I am not sure whether the link of OTU which we calculate represent the edge stablity?

**Comment by hmamine** [comment]
> Sorry for the extreme delay, somehow I didn't see this issue...
> We don't have p-values per se, but a good proxy is the edge stability which you can extract from spiec.easi output using the function `getOptMerge`. This will give you an adjacency matrix with a number between 0-1, corresponding to the fraction of networks, constructed with 80% subsamples, that also contained that edge. This isn't exactly an empirical p-value (like SparCC gives you) since we use sampling without replacement rather than the bootstrap, but the principle is similar.

Is it though possible to have p-values when using SparCC via SpiecEasi R-package? 
Also, I wondering what to set a cut-off of values that correspond to a p-value in SparCC, to be able to compare both networks? 
Many thanks, 
Amine

**Comment by zdk123** [comment]
@hmamine: yes: see the functions `sparccboot` and `pval.sparccboot`.

I don't think there would be a global cuttoff that would be meaningful for both methods, but for a specific dataset you could plot 1-stability vs sparcc pvals and see if there is any obvious breakpoint.
