### ISSUE TITLE
Input as count data or relative abundance?

### ISSUE THREAD

**Issue by koopkaup** [zdk123/SpiecEasi#64]
Should the OTU table represent absolute numbers or relative abundance? If it has count data then does SpiecEasi recognize that and transform it to relative numbers?

Thanks
Kristjan

**Comment by zdk123** [comment]
All inputs are assumed to be counts, and normalization is always done internally.

**Comment by Mataivic** [comment]
I have a similar question : my abundance table is made of DNA barcodes counts. Do I still need to normalize according to sampling depth before passing the table in SpiecEasi ? (I guess the answer is yes)

**Comment by zdk123** [comment]
Same answer as above. spiec.easi normalizes internally. Please pass in raw counts.

**Comment by zdk123** [comment]
Added warning in #71
