### ISSUE TITLE
Plot_network error in dimnames

### ISSUE THREAD

**Issue by TaylerChicoine** [zdk123/SpiecEasi#67]
Hello,

I'm using the phyloseq-spieceasi wrapper to try and use the plot_network function. the spiec.easi function and adj2igraph seem to work fine. My phyloseq object is NeighID. Code and error below, thanks for your help! 

se.mb.family_SLSL60 <- spiec.easi(NeighID, method='mb', lambda.min.ratio=1e-2,
                           nlambda=20, icov.select.params=list(rep.num=50)
>>Pulsar-selected refit of sparseiCov 
Path length: 20 
Graph dim:   268 
Criterion:
  stars... sparsity 0.021

ig.family_SLSL60 <- adj2igraph(getRefit(se.mb.family_SLSL60),  vertex.attr=list(name=taxa_names(NeighID)))
>> IGRAPH 23a8e08 UNW- 268 754 -- 
+ attr: name (v/c), weight (e/n)
+ edges from 23a8e08 (vertex names):
 [1] OTU3   --OTU138   OTU3 etc...

However, when I try and plot network: plot_network(ig.family_SLSL60, NeighID, type='taxa', color="Rank3"), I get the following error:
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent

**Comment by zdk123** [comment]
I think the `tax_table` in your phyloseq object is malformed. I was able to reproduce this bug by introducing some NAs. Try replacing NAs with empty strings.

`plot_network` is a phyloseq function, so if you think this is a bug, you should file an issue over there.

**Comment by TaylerChicoine** [comment]
Thanks for your response! You're right - that seems to be the issue. 
I tried to lump my otus by a higher taxonomic resolution with tax_glom from phylsoeq but this results in many NAs. Does anyone know how to change the NAs in a phyloseq object to an empty string?

**Comment by zdk123** [comment]
The `tax_table` function in phyloseq is also an assignment operator and the tax_table is also subsettable, so this should work:

    tax_table(phy)[is.na(tax_table(phy))] <- ""

where `phy` is the phyloseq object, of course.

**Comment by TaylerChicoine** [comment]
Thanks for your help!
