### ISSUE TITLE
EXPR must be a length 1 vector

### ISSUE THREAD

**Issue by longleyr** [zdk123/SpiecEasi#69]
Hello,
I am trying to build a  spiec easi network using a phyloseq object using the following code:
t2v2_spiec <- spiec.easi(physeq_object_filt_obj1_V2_no_till,huge::huge, method='mb', lambda.min.ratio=0.01,nlambda=30, pulsar.params=list(rep.num=100))

I inserted the huge::huge command to fix the following error: Error: 'huge.mb' is not an exported object from 'namespace:huge'

I am now receiving the following error:
 Error in switch(sel.criterion, stars = "stars", bstars = "stars", stop("Unknown selection criterion")) : 
  EXPR must be a length 1 vector 

Do you have any idea what could be causing this?

Thanks,
Reid

**Comment by zdk123** [comment]
I have a fix in the _patch_ branch (f009a82), for huge 1.3 but it is currently failing a test (that is working in master) so use at your own risk.

That being said, your function call here is invalid. `spiec.easi` does not support passing in an arbitrary functions. Your `huge::huge` positional argument is getting matched to the `sel.criterion`, which is not a valid data type or option for this argument.

**Comment by zdk123** [comment]
fixed in PR #71, tracking only in #68
