### ISSUE TITLE
Regarding sparCc code.

### ISSUE THREAD

**Issue by achaldhariwal** [zdk123/SpiecEasi#7]
Can you please tell me what is variable R in function(sparccboot) or what are the parameter should I provide in order to use this function .is it the number of time in need to bootstrap the sample because when i am providing its value as 100 or 1000 . R provide such error:

> bootdata<-sparccboot(data)
> Error in boot::boot(data, statisticboot, R = R, parallel = "multicore",  : 
>   number of items to replace is not a multiple of replacement length

**Comment by zdk123** [comment]
R is the number of bootstraps to sparCC over.

I am unable to replicate this error using a standard numeric data matrix. Can you provide your `data` (or an example of it) to test if this is actually a bug?

**Comment by zdk123** [comment]
@achaldhariwal: can you run

    save(data, file="exData.RData")

and host the resulting 'exData.RData' file to a public link on the internet (dropbox or google drive) and share that instead? I need to inspect the R object, not just the raw counts as you've posted here.

Thanks.

**Comment by achaldhariwal** [comment]
I am sharing the R data file.<https://www.dropbox.com/s/99s2zy9ow5qloy8/spardata.RData?dl=0>


<https://www.dropbox.com/s/99s2zy9ow5qloy8/spardata.RData?dl=0>

Thanking you,<https://www.dropbox.com/s/99s2zy9ow5qloy8/spardata.RData?dl=0>

Achal
<https://www.dropbox.com/s/99s2zy9ow5qloy8/spardata.RData?dl=0>


<https://www.dropbox.com/s/99s2zy9ow5qloy8/spardata.RData?dl=0>

https://www.dropbox.com/s/99s2zy9ow5qloy8/spardata.RData?dl=0

[https://cf.dropboxstatic.com/static/images/icons128/page_white.png]<https://www.dropbox.com/s/99s2zy9ow5qloy8/spardata.RData?dl=0>

spardata.RData<https://www.dropbox.com/s/99s2zy9ow5qloy8/spardata.RData?dl=0>
www.dropbox.com
Shared with Dropbox



________________________________

**Comment by zdk123** [comment]
So I am not able to replicate this error with the data you provided. Running

     out <- sparccboot(spardata, R=10)

returns without complaint. Can you confirm you are getting an error in running the above code?

thanks,

**Comment by achaldhariwal** [comment]
[cid:2cb2bb31-e84d-4b92-9215-e3c8734e099e]


I am still getting error


Thanks,

Achal

________________________________

**Comment by zdk123** [comment]
What about another data source? Can you try using the American gut project, included as the example in the readme?

**Comment by achaldhariwal** [comment]
Dear kurtz,


yeah I have tried with that also its still not working.Does it have any relationship with the Spiec easi package (because I cant able to install it).but in my understanding sparCC has to run normally by itself.


Thanking you,

Achal

________________________________

**Comment by achaldhariwal** [comment]
Dear Kurtz,


Also I need to ask you in the example of (american gut) used in SpiecEasi .For creation of sparCC network (you have used only sparcc function and haven't used any other sparccboot function or else . ) While in orignal sparCC they have used two sided p-value file rather than directly using correlation matrix.I am not sure what would be the exact effect of such way on the output of sparCC.


Thanking you,


Achal


________________________________

**Comment by zdk123** [comment]
Hi Achal,

  Yes, this version of sparCC is included in this SpiecEasi package. You definitely need to install SpiecEasi to run `sparcc` or `sparccboot`. I didn't run the bootstrapped version of sparCC in the readme, for the sake of brevity, but `sparccboot` also recreates the behavior from the original python package (and includes some options for parallelization). 

  I'm a bit mystified how you were able to run `sparccboot` at all if you haven't installed the package. What errors are you getting? Please make sure you have an up to date version of R and devtools before proceeding.

**Comment by achaldhariwal** [comment]
Currently, Iam able to install spiec easi package and working with it.But i need to ask you like will there be any significant difference in networks if I used bootstrapped sparcc as compared to without bootstrapped one.

Thanking you

**Comment by zdk123** [comment]
bootstrap is to compute empirical p-values (which is similar to, though not exactly the same method as Jonathan Friedman's original implementation). The correlation values will be the same.
