### ISSUE TITLE
Unexpected error running in parallel

### ISSUE THREAD

**Issue by ElDeveloper** [zdk123/SpiecEasi#8]
I got the error below when I tried to run the main function using 8 cores, like this:

```
se.before.xxx = spiec.easi(before.xxx, method='mb', lambda.min.ratio=1e-2,
                           nlambda=20, icov.select.params=list(rep.num=20, ncores=8))
```

```
Normalizing/clr transformation of data with pseudocount ...
Inverse Covariance Estimation with mb ...
Model selection with stars ...
Warning message:
In parallel::mclapply(1:rep.num, function(i) {: scheduled core 1 encountered error in user code, all values of the job will be affected
Error: not-yet-implemented method for +(<character>, <dgCMatrix>).
 ->>  Ask the package authors to implement the missing feature.
```

**Comment by zdk123** [comment]
Unless you pasted the wrong code here, you don't seem to actually be running in multicore... It should be run like this:

```
se.before.xxx = spiec.easi(before.xxx, method='mb', lambda.min.ratio=1e-2,
                           nlambda=20, icov.select.params=list(rep.num=20, ncores=8))
```

This wouldn't explain this error though. Can you provide some more information about the data or [part of] the data itself? I'm not sure where the 'character' data type is coming in.

**Comment by ElDeveloper** [comment]
@zdk123, my bad, I pasted the wrong code, I was running the code as in your post (I have now updated my original post).

There nothing special with the input table (that I know of). I tried to find a way to reproduce the error, but I wasn't able to find the original offending table.

**Comment by zdk123** [comment]
To clarify, you are no longer getting the error?

**Comment by ElDeveloper** [comment]
Just to be clear, I did see the error with one of my files. I tried looking for the file (even through TimeMachine ⏳) but I couldn't find it, that's the reason why I can't reproduce the error.

So I will close this for now.
