### ISSUE TITLE
Converting network to igraph with weights

### ISSUE THREAD

**Issue by apftwahkic** [zdk123/SpiecEasi#81]
Hi there

I am trying to convert my SpiecEasi network into an igraph with edge weights (so I can run a weighted community analysis) and having some difficulty - whilst I can extract the weights I'm not sure I am adding them correctly when I convert my SpiecEasi network to igraph.

My code:

```{r}
Net<- spiec.easi(asvs,
                            lambda.min.ratio=1e-1,
                            nlambda=100,
                            method='mb', 
                            pulsar.params=args)

#This extracts weights with no problem following patch (many thanks for that!)
bm <- symBeta(getOptBeta(Net), mode="maxabs")
diag(bm) <- 0

#But this produces a warning that suggests the weights are not  being added correctly 
FG.ig <- adj2igraph(getRefit(Net),
                  diag=TRUE,
                  edge.attr=list(weight=bm) ,
                  vertex.attr = list(name=taxa_names(physeq.full)))

[number of items to replace is not a multiple of replacement length ]
```

Should I just use: 

```{r}
FG .ig<- graph.adjacency(Net, weighted = T, mode="undirected") 
```
and not include the optimal graph path?  

Many thanks in advance!

**Comment by zdk123** [comment]
If all you need is weights (and not other edge attributes), you can pass the betas as the adjacency.

This should work:
```
FG.ig <- adj2igraph(bm,
                  diag=TRUE,
                  vertex.attr = list(name=taxa_names(physeq.full)))
```

If you want to attach other edge attributes, they should be passed in as an edge list, not a symmetric matrix.
```
FG.ig <- adj2igraph(getRefit(Net),
                  diag=TRUE,
                  edge.attr=list(weight=Matrix::summary(t(bm))) ,
                  vertex.attr = list(name=taxa_names(physeq.full)))
```

I realize the documentation is sparse here - I'll add that for an upcoming release.

**Comment by apftwahkic** [comment]
Perfect, thank you so much!

**Comment by apftwahkic** [comment]
Apologies, I'm still getting the same error as before  'number of items to replace is not a multiple of replacement length'

I'm after the second option preferably; should I still be extracting the 'bm' objects as 

```
bm <- symBeta(getOptBeta(Net), mode="maxabs")
diag(bm) <- 0
```

Very much appreciated and apologies for double commenting!

**Comment by zdk123** [comment]
There may be explicit zeros in the refit network (which I would consider a small bug on my end).

Try:

```
FG.ig <- adj2igraph(Matrix::drop0(getRefit(Net)),
                  edge.attr=list(weight=Matrix::summary(t(bm))) ,
                  vertex.attr = list(name=taxa_names(physeq.full)))
```

**Comment by apftwahkic** [comment]
Great, thanks so much, that seems to have worked!

**Comment by apftwahkic** [comment]
Thanks so much - that's let me convert it to an igraph object, however there now seems to be an issue with that - following the above code,
```
plot.igraph(FG.ig)
Error in layout_with_fr(graph, dim = dim, ...) : (list) object cannot be coerced to type 'double'

FG.ig[]
Error in get.adjacency.sparse(graph, type = type, attr = attr, edges = edges,  : 
  Sparse matrices must be either numeric or logical,and the edge attribute is not
```

**Comment by zdk123** [comment]
Apologies, there's a typo on my part. `Matrix::summary(t(bm))` is a 3 column matrix where column 3 are the 'weights'. The weights, therefore need to be just the vector in column 3.

```
weights <- Matrix::summary(t(bm))[,3]
FG.ig <- adj2igraph(Matrix::drop0(getRefit(Net)),
                   edge.attr=list(weight=weights),
                  vertex.attr = list(name=colnames(physeq.full)))
```

That being said, not all igraph layouts respect negative weights, so you may want to use the following map to the positive orthant:
```
weights <- (1-Matrix::summary(t(bm))[,3])/2
```

**Comment by apftwahkic** [comment]
Thank you very much! That's worked, hurrah (with taxa_names for extracting them from physeq.full in the vertex.attr, rather than colnames?) 

Thank you!

**Comment by Gian77** [comment]
Hello @zdk123 and @zdk123 

I also am trying to obtain edges weights and I am having this following error:

`> spiec_prok <- spiec.easi(physeq_prokaryote_filt, `
`+                          method="mb",`
`+                          nlambda=30,`
`+                          lambda.min.ratio=1e-2,`
`+                          pulsar.params=list(rep.num=99))`
`Applying data transformations...`
`Selecting model with pulsar using stars...`
`Fitting final estimate with mb...`
`done`

`> spiec_prok`
`Pulsar-selected refit of sparseiCov `
`Path length: 30 `
`Graph dim:   140 `
`Criterion:`
`  stars... sparsity 0.0186`

`> getStability(spiec_prok)`
`[1] 0.03970315`

`> beta_net <- symBeta(getOptBeta(spiec_prok), mode="maxabs")`
` Show Traceback`
 
 `Rerun with Debug`
 `Error in getOptBeta(spiec_prok) : Run spiec-easi with method="mb" `
`> `

Do you know what'happenign here? I have used `method = "mb"` in the function abaove.

Thank you very much in advance,

Gian

**Comment by choon-sim** [comment]
Hi @zdk123
"There may be explicit zeros in the refit network (which I would consider a small bug on my end)."
Can you share a little why there are zeros in the network? The edge weights in the MB method are an average of the two weights estimated from the corresponding beta scores of the taxa. Is it because one of the edge weight is a positive and the other edge weight is a negative so that the sign of the edge becomes uncertain? If so, would a reasonable conclusion be to say that there exist an edge between these two taxa but the sign of the edge cannot be reasonably determined?

**Comment by zdk123** [comment]
No, I think it's just how `huge` represents numerical zeros during construction of the sparse matrix. As in, small values such 1e-12 get converted into explicit zeros rather than just being dropped.
