### ISSUE TITLE
huge 1.3.2 compatibility

### ISSUE THREAD

**Issue by wanglu2014** [zdk123/SpiecEasi#82]
When I run "se.mb.amgut <- spiec.easi(amgut1.filt, method='mb', lambda.min.ratio=1e-2,
                          nlambda=20, pulsar.params=list(rep.num=50))"
Error : "Error in .Call("_huge_SPMBgraphlasso", x, lambda, nlambda, d, scr, as.matrix(0),  : 
  Incorrect number of arguments (7), expecting 10 for '_huge_SPMBgraphlasso'"

**Comment by wanglu2014** [comment]
Thank for you alway replay timely. I suspect it caused by package version mismatch. However, I installed spiec-easi 1.06, huge 1.32, still get this error. Could you kindly help me?

**Comment by zdk123** [comment]
Can you try downgrading to huge 1.3.1? That is the most recent version I have tested.

**Comment by wanglu2014** [comment]
I have downgrade huge to 1.3.1, and reinstall spiec-easi 1.06, get error "Error: 'huge.mb' is not an exported object from 'namespace:huge'"

**Comment by wanglu2014** [comment]
By the way, when calculate crossdomain edges, you recommand 'mb' or 'glasso'?

**Comment by wanglu2014** [comment]
> 
> 
> Can you try downgrading to huge 1.3.1? That is the most recent version I have tested.

I closed R, reopen and reload it. It worked, with spiec-easi 1.06 and huge 1.31. Sorry to bother you : )

**Comment by zdk123** [comment]
thanks. I plan to more rigorously test huge 1.3.2 compatibility in a future release.

**Comment by wanglu2014** [comment]
> 
> 
> thanks. I plan to more rigorously test huge 1.3.2 compatibility in a future release.
What is your recommandation to calculate crossdomain edges, 'mb' or 'glasso' ?

**Comment by zdk123** [comment]
No specific recommendations but we did use glasso in the paper:
https://www.ncbi.nlm.nih.gov/pubmed/29335027
