### ISSUE TITLE
rzipois() generates zero samples

### ISSUE THREAD

**Issue by t-pollington** [zdk123/SpiecEasi#83]
This example shows two zeroes being created by the zero-truncated Poisson distribution which should not be possible as its support is the positive integers only.
``` r
set.seed(0)
SpiecEasi::rzipois(n = 10,lambda = 1,pstr0 = 0)
#>  [1] 2 0 1 1 2 0 2 3 1 1
```

<sup>Created on 2019-04-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by zdk123** [comment]
This is the zero *inflated* Poisson. Setting pstr0=0 reduces the model to standard Poisson, which does have support on zeros.

**Comment by t-pollington** [comment]
:man_facepalming: sorry, my bad.
