### ISSUE TITLE
Extracting weights and plot with igraph

### ISSUE THREAD

**Issue by Gian77** [zdk123/SpiecEasi#84]
Hello @zdk123

Like reported in a previous Issue, I also am trying to obtain edges weights and I am having this following error:

`> spiec_prok <- spiec.easi(physeq_prokaryote_filt, `
`+                          method="mb",`
`+                          nlambda=30,`
`+                          lambda.min.ratio=1e-2,`
`+                          pulsar.params=list(rep.num=99))`
`Applying data transformations...`
`Selecting model with pulsar using stars...`
`Fitting final estimate with mb...`
`done`

`> spiec_prok`
`Pulsar-selected refit of sparseiCov `
`Path length: 30 `
`Graph dim:   140 `
`Criterion:`
`  stars... sparsity 0.0186`

`> getStability(spiec_prok)`
`[1] 0.03970315`

`> beta_net <- symBeta(getOptBeta(spiec_prok), mode="maxabs")`
` Show Traceback`
 
 `Rerun with Debug`
 `Error in getOptBeta(spiec_prok) : Run spiec-easi with method="mb" `
`> `

Do you know what's happening here? I have used `method = "mb"` in the function above.

Thank you very much in advance,

Gian

**Comment by zdk123** [comment]
can you post `sessionInfo` output? I suspect one or more packages are out of date.

**Comment by Gian77** [comment]
Sure! Thank you for all your help.

`> sessionInfo()`
`R version 3.4.4 (2018-03-15)`
`Platform: x86_64-pc-linux-gnu (64-bit)`
`Running under: Ubuntu 16.04.6 LTS`

`Matrix products: default`
`BLAS: /usr/lib/libblas/libblas.so.3.6.0`
`LAPACK: /usr/lib/lapack/liblapack.so.3.6.0`

`locale:`
` [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C               LC_TIME=en_CA.UTF-8   `     `LC_COLLATE=en_CA.UTF-8     LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8   `
` [7] LC_PAPER=en_CA.UTF-8       LC_NAME=C                  LC_ADDRESS=C    `           `LC_TELEPHONE=C             LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C    `   

`attached base packages:`
`[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base`     

`other attached packages:`
` [1] MCL_1.0              qgraph_1.6.1         huge_1.3.2           MASS_7.3-51.1        igraph_1.2.4     `    `SpiecEasi_1.0.6      ape_5.2             `
` [8] Biostrings_2.44.2    XVector_0.16.0       IRanges_2.10.5       S4Vectors_0.14.7     dplyr_0.8.0.1   `     `vegan_2.5-4          lattice_0.20-38     `
`[15] permute_0.9-4        ggplot2_3.1.0        phyloseq_1.20.0      metagenomeSeq_1.18.0 ``RColorBrewer_1.1-2   glmnet_2.0-16        foreach_1.4.4       `
`[22] Matrix_1.2-16        limma_3.32.10        Biobase_2.36.2       BiocGenerics_0.22.1 `

`loaded via a namespace (and not attached):`
` [1] nlme_3.1-137          bitops_1.0-6          matrixStats_0.54.0    httr_1.4.0            backports_1.1.3 `      `tools_3.4.4           R6_2.4.0             `
` [8] d3Network_0.5.2.1     rpart_4.1-13          KernSmooth_2.23-15    Hmisc_4.2-0      `     `lazyeval_0.2.1        mgcv_1.8-28           colorspace_1.4-0     
`[15] ade4_1.7-13           nnet_7.3-12           GetoptLong_0.1.7      withr_2.1.2.9000      mnormt_1.5-5  `        `tidyselect_0.2.5      gridExtra_2.3  `      `
`[22] compiler_3.4.4        fdrtool_1.2.15        htmlTable_1.13.1      expm_0.999-3          iNEXT_2.0.19`    `      `plotly_4.8.0          checkmate_1.9.1`      `
`[29] caTools_1.17.1.2      scales_1.0.0.9000     psych_1.8.12          pbapply_1.4-0         `pbivnorm_0.6.0`        `stringr_1.4.0         digest_0.6.18`       ` 
`[36] foreign_0.8-71        base64enc_0.1-3       jpeg_0.1-8            pkgconfig_2.0.2       htmltools_0.3.6 `      `htmlwidgets_1.3       rlang_0.3.1`          `
`[43] GlobalOptions_0.1.0   rstudioapi_0.9.0      VGAM_1.1-1            shape_1.4.4           jsonlite_1.6     `     `gtools_3.8.1          acepack_1.4.1`        `
`[50] magrittr_1.5          Formula_1.2-3         biomformat_1.4.0      Rcpp_1.0.1            munsell_0.5.0  `       `abind_1.4-5           whisker_0.3-2`        `
`[57] stringi_1.3.1         zlibbioc_1.22.0       rhdf5_2.20.0          gplots_3.0.1.1        plyr_1.8.4     `       `lavaan_0.6-3          grid_3.4.4  `         
`[64] gdata_2.18.0          crayon_1.3.4          cowplot_0.9.4         splines_3.4.4         multtest_2.32.0 `      `circlize_0.4.5        knitr_1.22           `
`[71] ComplexHeatmap_1.99.5 pillar_1.3.1          rjson_0.2.20          pulsar_0.3.5          corpcor_1.6.9 `        `BDgraph_2.57          reshape2_1.4.3       `
`[78] codetools_0.2-16      glue_1.3.0            latticeExtra_0.6-28   data.table_1.12.0     png_0.1-7    `         `gtable_0.2.0          purrr_0.3.1          `
`[85] tidyr_0.8.3           assertthat_0.2.0      xfun_0.5              glasso_1.10           survival_2.43-3       `viridisLite_0.3.0     tibble_2.0.1`
`[92] iterators_1.0.10      ggm_2.3               cluster_2.0.7-1      `

**Comment by zdk123** [comment]
Can you do two more things please:

post the output of `spiec_prok$est$method`
and try the American gut example in the readme to see if the error reproduces there.
thanks

**Comment by Gian77** [comment]
My pleasure. Please see below

`> spiec_prok$est$method`
`[1] "mb"`

`> data(amgut1.filt)`
`> se.mb.amgut <- spiec.easi(amgut1.filt, method='mb', lambda.min.ratio=1e-2,`
`+                           nlambda=20, pulsar.params=list(rep.num=50))`

`> se.mb.amgut`
`Pulsar-selected refit of sparseiCov `
`Path length: 20 `
`Graph dim:   127 `
`Criterion:`
 ` stars... sparsity 0.0182`

`> symBeta(getOptBeta(se.mb.amgut), mode="maxabs")`
 `Show Traceback`
 
 `Rerun with Debug`
 `Error in getOptBeta(se.mb.amgut) : Run spiec-easi with method="mb" `

Thanks,

Gian

**Comment by zdk123** [comment]
This is odd... updating to latest SpiecEasi and pulsar packages should have resolved this, since `getOptBeta` [should] simply check that `spiec_prok$est$method` is equal to "mb". I know from the sessionInfo looks like you are already up to date.


 Can you remove and reinstall SpiecEasi from the current master, just in case?

**Comment by Gian77** [comment]
I did remove and reinstall SpiecEasi as you suggested. When I loaded the package I noticed that I had some object - don't know why - in my the  `.GlobalEnv` that were masking some SpiecEasi functions

`> library("SpiecEasi"); packageVersion("SpiecEasi")`
`Attaching package: ‘SpiecEasi’`
`The following objects are masked _by_ ‘.GlobalEnv’:`
 `   getOptBeta, getOptMerge, symBeta`
`[1] ‘1.0.6’`

So I removed those objects, restared R, and tried again to calculate the weights.

`> library("SpiecEasi"); packageVersion("SpiecEasi")`
`[1] ‘1.0.6’`

`> data(amgut1.filt)`
`> se.mb.amgut <- spiec.easi(amgut1.filt, method='mb', lambda.min.ratio=1e-2,`
`+                           nlambda=20, pulsar.params=list(rep.num=50))`
`Applying data transformations...`
`Selecting model with pulsar using stars...`
`Fitting final estimate with mb...`
`done`
`> se.mb.amgut$est$method`
`[1] "mb"`
`> sebeta <- symBeta(getOptBeta(se.mb.amgut), mode="maxabs")`

It calculates it. But then I got this error - if that is an error.

`> sebeta`
`127 x 127 sparse Matrix of class "dsCMatrix"`
`Error in isFALSE(suppRows) : could not find function "isFALSE"`

If I look at the structure looks fine to me, right?

`> str(sebeta)`
`Formal class 'dsCMatrix' [package "Matrix"] with 7 slots`
`  ..@ i       : int [1:147] 3 4 1 11 9 3 12 26 27 24 ...`
`  ..@ p       : int [1:128] 0 0 0 0 0 0 0 0 0 0 ...`
`  ..@ Dim     : int [1:2] 127 127`
`  ..@ Dimnames:List of 2`
`  .. ..$ : NULL`
`  .. ..$ : NULL`
`  ..@ x       : num [1:147] 0.10575 -0.00983 0.61745 0.00301 0.0351 ...`
`  ..@ uplo    : chr "U"`
`  ..@ factors : list()`

**Comment by zdk123** [comment]
Perhaps you have more stale objects in your global environment, but I would try starting with a fresh install of the `Matrix` too. Oddly, I'm pretty sure `isFALSE` is a base function but maybe Matrix is overloading it somehow.

**Comment by Gian77** [comment]
And even more oddly, when I tried to run the whole code and extract the weights, it worked. I can add weighed edges to my network if I like now. I will post the code tomorrow if you think is useful. Thanks a lot for your help!

Gian

**Comment by gdanetzk** [comment]
@Gian77 I would be interested in your code!

**Comment by Gian77** [comment]
Hi @gdanetzk 

Try looking into this github repo for the code

https://github.com/Gian77/Scientific-Papers-R-Code/tree/master/Benucci_etal_2022_DeepSoilMicrobiome

Hope it helps :)

G
