### ISSUE TITLE
getOptX doesn't type check input object

### ISSUE THREAD

**Issue by xuebaliang** [zdk123/SpiecEasi#86]
hello, I have a question about the procedure for estimating the inverse covariance matrix. The below is my code:
**for mb method:**
 mb.res = sparseiCov(data = clr.data, method = 'mb')
 mb.icov = getOptBeta(mb.res)
**for gl methods:**
 gl.res = sparseiCov(clr.data, method = 'glasso')
 gl.icov = getOptiCov(gl.res)
where the clr.data is the data matrix after implement central log ratio transformation.
However, i get the above error.
But when i use your code from two yeas ago, it works, like this:
**for mb method**
 mb.res = sparseiCov(data = clr.data, method = 'mb', lambda.min.ratio = 1e-3, nlambda = 15)
 mb.res = icov.select(mb.res, criterion = 'stars')
 mb.icov = symBeta(getOptBeta(mb.res), mode='ave')
**for gl method**
 gl.res = sparseiCov(clr.data, method = 'glasso', lambda.min.ratio = 1e-3, nlambda = 15)
 gl.res = icov.select(gl.res, criterion = 'stars')
 gl.icov = gl.res$opt.icov
therefore, i want to know how to get the inverse covariance matrix of two methods from your newest code. I hope you can write the code for me in my data form or the way i can understand. Thanks very much.

**Comment by zdk123** [comment]
I am actually surprised that the old code worked. The `sparseiCov` doesn't do model selection and so there is no optimal graph to choose from. 
As explained in the README, please run `spiec.easi(clr.data, method='mb')`.

**Comment by xuebaliang** [comment]
Thanks for your answer. thus i should do:
for mb method, mb.res = spiec.easi(clr.data, method='mb',...), but is the object mb.res the optimal graph? or i should do more to obtain the unique precision matrix, such as mb.icov = getOptBeta(mb.res)?

**Comment by zdk123** [comment]
the latter is the correct approach. See the README for an example run: https://github.com/zdk123/SpiecEasi#analysis-of-american-gut-data

**Comment by xuebaliang** [comment]
ok，thank you,  i just run the whole code as you say. But i can't find the optimal graph, namely the best estimated precision matrix through model selection.  For example, i just can get the below results:
huge::huge.roc(mb.res$est$path, graph, verbose=FALSE)
True Postive Rate: from 0 to 0.8514286 
False Positive Rate: from 0 to 1.022857 
Area under Curve: 0.6609116 
Maximum F1 Score: 0.6425384 
where mb.res is obtained by function  spiec.easi .

**Comment by zdk123** [comment]
I don't have enough information about your data / setup to judge this output behavior. However, this is now off-topic, so please file a new issue if you can describe the problem you are seeing together with a reproducible example.
thank you.
