### ISSUE TITLE
How to understand the positive and negative correlation of SpiecEasi?

### ISSUE THREAD

**Issue by wanglu2014** [zdk123/SpiecEasi#88]
By SpiecEasi introduction, we already known "edge weights are not directly comparable to SparCC (or Pearson/Spearman correlation coefficients)". The SpiecEasi edges are generally small, like '-0.003' and '0.002'. When positive and negative correlation values are so close, they were taken as real positive and negative correlations, or just correlations?
            Thank for your attention!

**Comment by zdk123** [comment]
The values are not related to sample correlations for two reasons. 1) SPIEC-EASI measures conditional independence (inverse covariance) not correlation 2) the magnitudes are shrunk towards zero.

Small values are therefore expected.
