### ISSUE TITLE
Not available for R v3.3.0?

### ISSUE THREAD

**Issue by geboro** [zdk123/SpiecEasi#9]
Any idea what changed in the last release?
Cheers,

**Comment by zdk123** [comment]
@geboro: Please provide more information. Are you getting this error from `install_packages`? SpiecEasi is not available on CRAN, you can use the devtools package to install from github. Instructions are here: https://github.com/zdk123/SpiecEasi#installation

**Comment by geboro** [comment]
Oh damn, this is embarrassing. 
Sorry and thanks!

**Comment by zdk123** [comment]
no problem, we've all had those days!
