### ISSUE TITLE
Edge length 

### ISSUE THREAD

**Issue by choon-sim** [zdk123/SpiecEasi#93]
Hi, I am wondering what does the length of an edge mean in the context of the mb model, and where can I find this value in the output? Thanks,

**Comment by zdk123** [comment]
I don't think I have ever used 'length' in the context of the MB model... Can you specify where you heard or read this?

**Comment by choon-sim** [comment]
I mean, it is just that when igraph plots the network, the nodes are placed apart from one another at a certain distance. Some nodes are reproducibly placed far apart from each other, while other nodes are reproducibly placed close to each other. I am wondering whether this has any meaning...

**Comment by zdk123** [comment]
It depends on which igraph layout method you are using and if you are using a weighted network  - possibly it relates to the magnitude of the coefficients. Also note that not all graph layouts correctly interpret signed edges. 
I recommend consulting the igraph documentation for more information as network plotting it an extensive topic.
