### ISSUE TITLE
Warning when plotting network

### ISSUE THREAD

**Issue by rozlynboutin** [zdk123/SpiecEasi#94]
Hi,

I am new to using Spiec-Easi, but am getting the following error when I try to graph the network:

Warning message:
attributes are not identical across measure variables; they will be dropped 

Is this something that I need to be worried about?

Thanks in advance!

**Comment by zdk123** [comment]
I believe this indicates NAs in some vertex attribute. I think it should be OK, unless can see if there is missing data?

**Comment by rozlynboutin** [comment]
Ok, great-thanks! I don't have any NAs in the table I input to speic-easi so I think it is probably ok. Thanks for the quick reply!

**Comment by zdk123** [comment]
the NAs vertex attributes are probably in the taxonomic assignments from phyloseq (e.g unknown genus or species = NA)
