### ISSUE TITLE
Installation trouble (OSX)

### ISSUE THREAD

**Issue by Mataivic** [zdk123/SpiecEasi#96]
Hello,

Someone from my lab is trying to install SpiecEasi but get this error :

```
> install_github("zdk123/SpiecEasi")
Downloading GitHub repo zdk123/SpiecEasi@master
tar: Failed to set default locale
tar: Failed to set default locale
   During startup - Warning messages:
   1: Setting LC_CTYPE failed, using "C"
   2: Setting LC_TIME failed, using "C"
   3: Setting LC_MESSAGES failed, using "C"
   4: Setting LC_MONETARY failed, using "C"
v  checking for file '/private/var/folders/f6/1qzqzbqn7yqgy003_3s94m_m0000gn/T/Rtmp8c2vOY/remotes20d74d3feaaa/zdk123-SpiecEasi-0d48baf/DESCRIPTION' ...
-  preparing 'SpiecEasi':
v  checking DESCRIPTION meta-information ...
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
   Removed empty directory 'SpiecEasi/inst'
-  looking to see if a 'data/datalist' file should be added
-  building 'SpiecEasi_1.0.6.tar.gz'
  
Error: (converted from warning) Setting LC_CTYPE failed, using "C"
Execution halted
Error: Failed to install 'SpiecEasi' from GitHub:
  (converted from warning) installation of package '/var/folders/f6/1qzqzbqn7yqgy003_3s94m_m0000gn/T//Rtmp8c2vOY/file20d789bb5ce/SpiecEasi_1.0.6.tar.gz' had non-zero exit status
```

I can't figure out what is the problem ; I don't know if it is due to OSX or the fact that it is a chinese computer (which might imply encoding conflicts or stuff like that).

I also used the command `system('defaults write org.R-project.R force.LANG en_US.UTF-8')` to fix the errors `tar: Failed to set default locale` but it did not do anything.

Maybe it is better to try with the conda package ?

Thanks.

**Comment by zdk123** [comment]
I haven't seen this error before, but since the only non-ASCII characters are in the package documentation, perhaps you can get away with simply quieting the warning.

I.e. set the environment variable `R_REMOTES_NO_ERRORS_FROM_WARNINGS=true` or `Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")) ` from within R, and try again.

**Comment by Mataivic** [comment]
It works ! Thanks :).
