### ISSUE TITLE
SPIEC-EASI won't get past "Selecting model with pulsar using stars..."

### ISSUE THREAD

**Issue by aalexiev** [zdk123/SpiecEasi#97]
Good day,

I've been trying to get SPIEC-EASI to work with my data for a couple days now, but have been unsuccessful. The data I'm using include 3 fungal OTU's and 1823 bacterial OTU's across 15 samples. Here is what I've tried:

- Using one matrix that contains both fungal AND bacterial OTU's among a shared set of sample ID's, I tried to use the Glasso and MB methods a few times. I varied lambda.min.ratio, nlambda, and rep.num in pulsar.params one by one, but each time it would get stuck on "Selecting model with pulsar using stars...". "top" in terminal showed that R would run for a few minutes then stop. Is it not able to get select a model in this case, and why would that be the case?

- Using two matrices, one with fungal OTU's and one with bacterial OTU's, with the same sample ID's in the same order, I tried to run the model as suggested in the github tutorial section "Cross domain interactions" but keep getting the error "Error in if (max < min) stop("Did you flip min and max?") : 
  argument is of length zero"

I'm not sure what the error means, i.e. which min and max would be flipped? What parameter in the script would I need to change in this case? I am not using phyloseq objects as the example in this section suggests, is this what is causing a problem?

Any help is appreciated, I would really like to use SPIEC-EASI since I think it is the best network model currently for microbial community work, but I'm starting to worry that my data just isn't suitable for a network analysis.

**Comment by zdk123** [comment]
Hi Alex,
 Don't despair! I still recommend option number 2, but the problem sounds like a bug on our end.
Or at least if the data is formatted oddly, then we aren't catching the real error early enough... 

Here, the job is failing early on when we try to get the values for the lambda path. This makes me think there are bad values in the dataset. I've seen this type of thing before when, for example, there is a column of all zero counts.

Any chance you can share your data / perhaps offline?

**Comment by aalexiev** [comment]
Hi Zachary,

I can definitely share the data. Would email be ok? I see an email listed on your github profile, if that is a good one to send to.

Also, as a note, that error I was getting with option #2 went away after I restarted R...it is possible I messed with my data iteratively too many times in an attempt to get the matrices I wanted and ended up with something weird. Now option #2 will start running without that error, but again gets stuck on "Selecting model..." unfortunately.

**Comment by zdk123** [comment]
zdkurtz[at]gmail.com

**Comment by zdk123** [comment]
resolved offline

**Comment by GitHubShen** [comment]
Hi Zachary and Alex,
Could you please offer any kind of help on how you finally solved this problem? 
I got similar error when running “se.bac<- spiec.easi(bac, method='MB', lambda.min.ratio=0.01, nlambda=50)” using my OTU table containning 36 samples and ~1000 OTUs. 
The errorr is "Error in if (max < min) stop("Did you flip min and max?") : 
  argument is of length zero". 
I would really appreciate your help. Have a good day!

**Comment by aalexiev** [comment]
Not sure if it'll be the same reason as in my dataset, but it was just a computing time issue for me! My data had a lot of OTUs that only occurred once so Zack suggested I filter those out. They likely aren't biologically relevant, especially for my particular question. Then I also ended up using the supercomputer at my institution to be able to run it. It might be worth looking into computing resources wherever you are, if you haven't already. I hadn't realized (but probably should have) how much computing power this needs.

**Comment by GitHubShen** [comment]
Thank you, Alex! My problem is solved finally. Yeah, the computing resources really matters! I used servers in my institution and it worked! Thanks!!!

**Comment by NehaMiSeq** [comment]
Hi 
I am trying Spiec-Easi to construct networks.
Getting an error:
Applying data transformations...
Error in if (max < min) stop("Did you flip min and max?") : 
  missing value where TRUE/FALSE needed

Any help would be appreciated. Thanks.

**Comment by NehaMiSeq** [comment]
Hi, 
I am trying to build a network with Spiec-Easi, getting an error after running the following,

phyloseq.obj=phyloseq(otu_table(otu.table_filtered,taxa_are_rows=TRUE))
> spiec.out=spiec.easi(phyloseq.obj, method = "mb", icov.select.params = list(rep.num = 20))
Applying data transformations...
Error in if (max < min) stop("Did you flip min and max?") : 
  missing value where TRUE/FALSE needed

I am unable to understand the error, seems there is problem with he data. 
Can anyone help?

**Comment by zdk123** [comment]
@NehaMiSeq If you want to send your data over I can try to reproduce the bug - probably there's an issue with your correlation matrix that's not being handled correctly by the software.

**Comment by flavien-maucourt** [comment]
Hi, 

First of all thanks zdk123 for your work ! 

I come accros the same problem than NehaMiseq and i can't figure it out myself. Anyone could you help me ?

**Comment by LiangLifeng** [comment]
I found Spiec-Easi didn't accept negative values.

**Comment by LiangLifeng** [comment]
I found Spiec-Easi didn't accept negative values.  library("mixOmics")
